@echo off

set BUILD=_build

set BZIP2=bzip2-1.0.8
set OPENSSL=openssl-1.1.1m
set NCURSES=ncurses-6.3
set GIT=git-2.34.1
set ICONV=libiconv-1.16
set LESS=less-590
set PUTTY=putty-0.76

cd %~dp0
if errorlevel 1 goto error

if not "%1" == "" goto :%1

del %BUILD%\libgcc_s_dw2-1.dll

:autorun

del %~dp0..\CD\AUTORUN.EXE
rmdir /S/Q %BUILD%\autorun

if not "%1" == "" goto next

:zlib

rmdir /S/Q %BUILD%\zlib

if not "%1" == "" goto next

:bzip2

del %BZIP2%\blocksort.o
del %BZIP2%\bzip2.exe
del %BZIP2%\bzip2.o
del %BZIP2%\bzip2recover.exe
del %BZIP2%\bzip2recover.o
del %BZIP2%\bzlib.o
del %BZIP2%\compress.o
del %BZIP2%\crctable.o
del %BZIP2%\decompress.o
del %BZIP2%\huffman.o
del %BZIP2%\libbz2.a
del %BZIP2%\randtable.o
del %BZIP2%\sample1.rb2
del %BZIP2%\sample1.tst
del %BZIP2%\sample2.rb2
del %BZIP2%\sample2.tst
del %BZIP2%\sample3.rb2
del %BZIP2%\sample3.tst
del %BZIP2%\bzip2-shared.exe
del %BZIP2%\libbz2.so.1.0
del %BZIP2%\libbz2.so.1.0.8
del %BZIP2%\bzip2.dll
del %BZIP2%\bzip2.dll.a

if not "%1" == "" goto next

:openssl

del %OPENSSL%\Makefile
del %OPENSSL%\Makefile.new
del %OPENSSL%\apps\CA.pl
del %OPENSSL%\apps\app_rand.d
del %OPENSSL%\apps\app_rand.o
del %OPENSSL%\apps\apps.d
del %OPENSSL%\apps\apps.o
del %OPENSSL%\apps\asn1pars.d
del %OPENSSL%\apps\asn1pars.o
del %OPENSSL%\apps\bf_prefix.d
del %OPENSSL%\apps\bf_prefix.o
del %OPENSSL%\apps\ca.d
del %OPENSSL%\apps\ca.o
del %OPENSSL%\apps\ciphers.d
del %OPENSSL%\apps\ciphers.o
del %OPENSSL%\apps\cms.d
del %OPENSSL%\apps\cms.o
del %OPENSSL%\apps\crl.d
del %OPENSSL%\apps\crl.o
del %OPENSSL%\apps\crl2p7.d
del %OPENSSL%\apps\crl2p7.o
del %OPENSSL%\apps\dgst.d
del %OPENSSL%\apps\dgst.o
del %OPENSSL%\apps\dhparam.d
del %OPENSSL%\apps\dhparam.o
del %OPENSSL%\apps\dsa.d
del %OPENSSL%\apps\dsa.o
del %OPENSSL%\apps\dsaparam.d
del %OPENSSL%\apps\dsaparam.o
del %OPENSSL%\apps\ec.d
del %OPENSSL%\apps\ec.o
del %OPENSSL%\apps\ecparam.d
del %OPENSSL%\apps\ecparam.o
del %OPENSSL%\apps\enc.d
del %OPENSSL%\apps\enc.o
del %OPENSSL%\apps\engine.d
del %OPENSSL%\apps\engine.o
del %OPENSSL%\apps\errstr.d
del %OPENSSL%\apps\errstr.o
del %OPENSSL%\apps\gendsa.d
del %OPENSSL%\apps\gendsa.o
del %OPENSSL%\apps\genpkey.d
del %OPENSSL%\apps\genpkey.o
del %OPENSSL%\apps\genrsa.d
del %OPENSSL%\apps\genrsa.o
del %OPENSSL%\apps\libapps.a
del %OPENSSL%\apps\libcrypto-1_1.dll
del %OPENSSL%\apps\libssl-1_1.dll
del %OPENSSL%\apps\nseq.d
del %OPENSSL%\apps\nseq.o
del %OPENSSL%\apps\ocsp.d
del %OPENSSL%\apps\ocsp.o
del %OPENSSL%\apps\openssl.d
del %OPENSSL%\apps\openssl.exe
del %OPENSSL%\apps\openssl.o
del %OPENSSL%\apps\openssl.rc
del %OPENSSL%\apps\openssl.res.o
del %OPENSSL%\apps\opt.d
del %OPENSSL%\apps\opt.o
del %OPENSSL%\apps\passwd.d
del %OPENSSL%\apps\passwd.o
del %OPENSSL%\apps\pkcs12.d
del %OPENSSL%\apps\pkcs12.o
del %OPENSSL%\apps\pkcs7.d
del %OPENSSL%\apps\pkcs7.o
del %OPENSSL%\apps\pkcs8.d
del %OPENSSL%\apps\pkcs8.o
del %OPENSSL%\apps\pkey.d
del %OPENSSL%\apps\pkey.o
del %OPENSSL%\apps\pkeyparam.d
del %OPENSSL%\apps\pkeyparam.o
del %OPENSSL%\apps\pkeyutl.d
del %OPENSSL%\apps\pkeyutl.o
del %OPENSSL%\apps\prime.d
del %OPENSSL%\apps\prime.o
del %OPENSSL%\apps\progs.h
del %OPENSSL%\apps\rand.d
del %OPENSSL%\apps\rand.o
del %OPENSSL%\apps\rehash.d
del %OPENSSL%\apps\rehash.o
del %OPENSSL%\apps\req.d
del %OPENSSL%\apps\req.o
del %OPENSSL%\apps\rsa.d
del %OPENSSL%\apps\rsa.o
del %OPENSSL%\apps\rsautl.d
del %OPENSSL%\apps\rsautl.o
del %OPENSSL%\apps\s_cb.d
del %OPENSSL%\apps\s_cb.o
del %OPENSSL%\apps\s_client.d
del %OPENSSL%\apps\s_client.o
del %OPENSSL%\apps\s_server.d
del %OPENSSL%\apps\s_server.o
del %OPENSSL%\apps\s_socket.d
del %OPENSSL%\apps\s_socket.o
del %OPENSSL%\apps\s_time.d
del %OPENSSL%\apps\s_time.o
del %OPENSSL%\apps\sess_id.d
del %OPENSSL%\apps\sess_id.o
del %OPENSSL%\apps\smime.d
del %OPENSSL%\apps\smime.o
del %OPENSSL%\apps\speed.d
del %OPENSSL%\apps\speed.o
del %OPENSSL%\apps\spkac.d
del %OPENSSL%\apps\spkac.o
del %OPENSSL%\apps\srp.d
del %OPENSSL%\apps\srp.o
del %OPENSSL%\apps\storeutl.d
del %OPENSSL%\apps\storeutl.o
del %OPENSSL%\apps\ts.d
del %OPENSSL%\apps\ts.o
del %OPENSSL%\apps\tsget.pl
del %OPENSSL%\apps\verify.d
del %OPENSSL%\apps\verify.o
del %OPENSSL%\apps\version.d
del %OPENSSL%\apps\version.o
del %OPENSSL%\apps\win32_init.d
del %OPENSSL%\apps\win32_init.o
del %OPENSSL%\apps\x509.d
del %OPENSSL%\apps\x509.o
del %OPENSSL%\configdata.pm
del %OPENSSL%\crypto\aes\aes_cbc.d
del %OPENSSL%\crypto\aes\aes_cbc.o
del %OPENSSL%\crypto\aes\aes_cfb.d
del %OPENSSL%\crypto\aes\aes_cfb.o
del %OPENSSL%\crypto\aes\aes_core.d
del %OPENSSL%\crypto\aes\aes_core.o
del %OPENSSL%\crypto\aes\aes_ecb.d
del %OPENSSL%\crypto\aes\aes_ecb.o
del %OPENSSL%\crypto\aes\aes_ige.d
del %OPENSSL%\crypto\aes\aes_ige.o
del %OPENSSL%\crypto\aes\aes_misc.d
del %OPENSSL%\crypto\aes\aes_misc.o
del %OPENSSL%\crypto\aes\aes_ofb.d
del %OPENSSL%\crypto\aes\aes_ofb.o
del %OPENSSL%\crypto\aes\aes_wrap.d
del %OPENSSL%\crypto\aes\aes_wrap.o
del %OPENSSL%\crypto\aes\aesni-x86.o
del %OPENSSL%\crypto\aes\aesni-x86.s
del %OPENSSL%\crypto\aes\vpaes-x86.o
del %OPENSSL%\crypto\aes\vpaes-x86.s
del %OPENSSL%\crypto\aria\aria.d
del %OPENSSL%\crypto\aria\aria.o
del %OPENSSL%\crypto\asn1\a_bitstr.d
del %OPENSSL%\crypto\asn1\a_bitstr.o
del %OPENSSL%\crypto\asn1\a_d2i_fp.d
del %OPENSSL%\crypto\asn1\a_d2i_fp.o
del %OPENSSL%\crypto\asn1\a_digest.d
del %OPENSSL%\crypto\asn1\a_digest.o
del %OPENSSL%\crypto\asn1\a_dup.d
del %OPENSSL%\crypto\asn1\a_dup.o
del %OPENSSL%\crypto\asn1\a_gentm.d
del %OPENSSL%\crypto\asn1\a_gentm.o
del %OPENSSL%\crypto\asn1\a_i2d_fp.d
del %OPENSSL%\crypto\asn1\a_i2d_fp.o
del %OPENSSL%\crypto\asn1\a_int.d
del %OPENSSL%\crypto\asn1\a_int.o
del %OPENSSL%\crypto\asn1\a_mbstr.d
del %OPENSSL%\crypto\asn1\a_mbstr.o
del %OPENSSL%\crypto\asn1\a_object.d
del %OPENSSL%\crypto\asn1\a_object.o
del %OPENSSL%\crypto\asn1\a_octet.d
del %OPENSSL%\crypto\asn1\a_octet.o
del %OPENSSL%\crypto\asn1\a_print.d
del %OPENSSL%\crypto\asn1\a_print.o
del %OPENSSL%\crypto\asn1\a_sign.d
del %OPENSSL%\crypto\asn1\a_sign.o
del %OPENSSL%\crypto\asn1\a_strex.d
del %OPENSSL%\crypto\asn1\a_strex.o
del %OPENSSL%\crypto\asn1\a_strnid.d
del %OPENSSL%\crypto\asn1\a_strnid.o
del %OPENSSL%\crypto\asn1\a_time.d
del %OPENSSL%\crypto\asn1\a_time.o
del %OPENSSL%\crypto\asn1\a_type.d
del %OPENSSL%\crypto\asn1\a_type.o
del %OPENSSL%\crypto\asn1\a_utctm.d
del %OPENSSL%\crypto\asn1\a_utctm.o
del %OPENSSL%\crypto\asn1\a_utf8.d
del %OPENSSL%\crypto\asn1\a_utf8.o
del %OPENSSL%\crypto\asn1\a_verify.d
del %OPENSSL%\crypto\asn1\a_verify.o
del %OPENSSL%\crypto\asn1\ameth_lib.d
del %OPENSSL%\crypto\asn1\ameth_lib.o
del %OPENSSL%\crypto\asn1\asn1_err.d
del %OPENSSL%\crypto\asn1\asn1_err.o
del %OPENSSL%\crypto\asn1\asn1_gen.d
del %OPENSSL%\crypto\asn1\asn1_gen.o
del %OPENSSL%\crypto\asn1\asn1_item_list.d
del %OPENSSL%\crypto\asn1\asn1_item_list.o
del %OPENSSL%\crypto\asn1\asn1_lib.d
del %OPENSSL%\crypto\asn1\asn1_lib.o
del %OPENSSL%\crypto\asn1\asn1_par.d
del %OPENSSL%\crypto\asn1\asn1_par.o
del %OPENSSL%\crypto\asn1\asn_mime.d
del %OPENSSL%\crypto\asn1\asn_mime.o
del %OPENSSL%\crypto\asn1\asn_moid.d
del %OPENSSL%\crypto\asn1\asn_moid.o
del %OPENSSL%\crypto\asn1\asn_mstbl.d
del %OPENSSL%\crypto\asn1\asn_mstbl.o
del %OPENSSL%\crypto\asn1\asn_pack.d
del %OPENSSL%\crypto\asn1\asn_pack.o
del %OPENSSL%\crypto\asn1\bio_asn1.d
del %OPENSSL%\crypto\asn1\bio_asn1.o
del %OPENSSL%\crypto\asn1\bio_ndef.d
del %OPENSSL%\crypto\asn1\bio_ndef.o
del %OPENSSL%\crypto\asn1\d2i_pr.d
del %OPENSSL%\crypto\asn1\d2i_pr.o
del %OPENSSL%\crypto\asn1\d2i_pu.d
del %OPENSSL%\crypto\asn1\d2i_pu.o
del %OPENSSL%\crypto\asn1\evp_asn1.d
del %OPENSSL%\crypto\asn1\evp_asn1.o
del %OPENSSL%\crypto\asn1\f_int.d
del %OPENSSL%\crypto\asn1\f_int.o
del %OPENSSL%\crypto\asn1\f_string.d
del %OPENSSL%\crypto\asn1\f_string.o
del %OPENSSL%\crypto\asn1\i2d_pr.d
del %OPENSSL%\crypto\asn1\i2d_pr.o
del %OPENSSL%\crypto\asn1\i2d_pu.d
del %OPENSSL%\crypto\asn1\i2d_pu.o
del %OPENSSL%\crypto\asn1\n_pkey.d
del %OPENSSL%\crypto\asn1\n_pkey.o
del %OPENSSL%\crypto\asn1\nsseq.d
del %OPENSSL%\crypto\asn1\nsseq.o
del %OPENSSL%\crypto\asn1\p5_pbe.d
del %OPENSSL%\crypto\asn1\p5_pbe.o
del %OPENSSL%\crypto\asn1\p5_pbev2.d
del %OPENSSL%\crypto\asn1\p5_pbev2.o
del %OPENSSL%\crypto\asn1\p5_scrypt.d
del %OPENSSL%\crypto\asn1\p5_scrypt.o
del %OPENSSL%\crypto\asn1\p8_pkey.d
del %OPENSSL%\crypto\asn1\p8_pkey.o
del %OPENSSL%\crypto\asn1\t_bitst.d
del %OPENSSL%\crypto\asn1\t_bitst.o
del %OPENSSL%\crypto\asn1\t_pkey.d
del %OPENSSL%\crypto\asn1\t_pkey.o
del %OPENSSL%\crypto\asn1\t_spki.d
del %OPENSSL%\crypto\asn1\t_spki.o
del %OPENSSL%\crypto\asn1\tasn_dec.d
del %OPENSSL%\crypto\asn1\tasn_dec.o
del %OPENSSL%\crypto\asn1\tasn_enc.d
del %OPENSSL%\crypto\asn1\tasn_enc.o
del %OPENSSL%\crypto\asn1\tasn_fre.d
del %OPENSSL%\crypto\asn1\tasn_fre.o
del %OPENSSL%\crypto\asn1\tasn_new.d
del %OPENSSL%\crypto\asn1\tasn_new.o
del %OPENSSL%\crypto\asn1\tasn_prn.d
del %OPENSSL%\crypto\asn1\tasn_prn.o
del %OPENSSL%\crypto\asn1\tasn_scn.d
del %OPENSSL%\crypto\asn1\tasn_scn.o
del %OPENSSL%\crypto\asn1\tasn_typ.d
del %OPENSSL%\crypto\asn1\tasn_typ.o
del %OPENSSL%\crypto\asn1\tasn_utl.d
del %OPENSSL%\crypto\asn1\tasn_utl.o
del %OPENSSL%\crypto\asn1\x_algor.d
del %OPENSSL%\crypto\asn1\x_algor.o
del %OPENSSL%\crypto\asn1\x_bignum.d
del %OPENSSL%\crypto\asn1\x_bignum.o
del %OPENSSL%\crypto\asn1\x_info.d
del %OPENSSL%\crypto\asn1\x_info.o
del %OPENSSL%\crypto\asn1\x_int64.d
del %OPENSSL%\crypto\asn1\x_int64.o
del %OPENSSL%\crypto\asn1\x_long.d
del %OPENSSL%\crypto\asn1\x_long.o
del %OPENSSL%\crypto\asn1\x_pkey.d
del %OPENSSL%\crypto\asn1\x_pkey.o
del %OPENSSL%\crypto\asn1\x_sig.d
del %OPENSSL%\crypto\asn1\x_sig.o
del %OPENSSL%\crypto\asn1\x_spki.d
del %OPENSSL%\crypto\asn1\x_spki.o
del %OPENSSL%\crypto\asn1\x_val.d
del %OPENSSL%\crypto\asn1\x_val.o
del %OPENSSL%\crypto\async\arch\async_null.d
del %OPENSSL%\crypto\async\arch\async_null.o
del %OPENSSL%\crypto\async\arch\async_posix.d
del %OPENSSL%\crypto\async\arch\async_posix.o
del %OPENSSL%\crypto\async\arch\async_win.d
del %OPENSSL%\crypto\async\arch\async_win.o
del %OPENSSL%\crypto\async\async.d
del %OPENSSL%\crypto\async\async.o
del %OPENSSL%\crypto\async\async_err.d
del %OPENSSL%\crypto\async\async_err.o
del %OPENSSL%\crypto\async\async_wait.d
del %OPENSSL%\crypto\async\async_wait.o
del %OPENSSL%\crypto\bf\bf-586.o
del %OPENSSL%\crypto\bf\bf-586.s
del %OPENSSL%\crypto\bf\bf_cfb64.d
del %OPENSSL%\crypto\bf\bf_cfb64.o
del %OPENSSL%\crypto\bf\bf_ecb.d
del %OPENSSL%\crypto\bf\bf_ecb.o
del %OPENSSL%\crypto\bf\bf_ofb64.d
del %OPENSSL%\crypto\bf\bf_ofb64.o
del %OPENSSL%\crypto\bf\bf_skey.d
del %OPENSSL%\crypto\bf\bf_skey.o
del %OPENSSL%\crypto\bio\b_addr.d
del %OPENSSL%\crypto\bio\b_addr.o
del %OPENSSL%\crypto\bio\b_dump.d
del %OPENSSL%\crypto\bio\b_dump.o
del %OPENSSL%\crypto\bio\b_print.d
del %OPENSSL%\crypto\bio\b_print.o
del %OPENSSL%\crypto\bio\b_sock.d
del %OPENSSL%\crypto\bio\b_sock.o
del %OPENSSL%\crypto\bio\b_sock2.d
del %OPENSSL%\crypto\bio\b_sock2.o
del %OPENSSL%\crypto\bio\bf_buff.d
del %OPENSSL%\crypto\bio\bf_buff.o
del %OPENSSL%\crypto\bio\bf_lbuf.d
del %OPENSSL%\crypto\bio\bf_lbuf.o
del %OPENSSL%\crypto\bio\bf_nbio.d
del %OPENSSL%\crypto\bio\bf_nbio.o
del %OPENSSL%\crypto\bio\bf_null.d
del %OPENSSL%\crypto\bio\bf_null.o
del %OPENSSL%\crypto\bio\bio_cb.d
del %OPENSSL%\crypto\bio\bio_cb.o
del %OPENSSL%\crypto\bio\bio_err.d
del %OPENSSL%\crypto\bio\bio_err.o
del %OPENSSL%\crypto\bio\bio_lib.d
del %OPENSSL%\crypto\bio\bio_lib.o
del %OPENSSL%\crypto\bio\bio_meth.d
del %OPENSSL%\crypto\bio\bio_meth.o
del %OPENSSL%\crypto\bio\bss_acpt.d
del %OPENSSL%\crypto\bio\bss_acpt.o
del %OPENSSL%\crypto\bio\bss_bio.d
del %OPENSSL%\crypto\bio\bss_bio.o
del %OPENSSL%\crypto\bio\bss_conn.d
del %OPENSSL%\crypto\bio\bss_conn.o
del %OPENSSL%\crypto\bio\bss_dgram.d
del %OPENSSL%\crypto\bio\bss_dgram.o
del %OPENSSL%\crypto\bio\bss_fd.d
del %OPENSSL%\crypto\bio\bss_fd.o
del %OPENSSL%\crypto\bio\bss_file.d
del %OPENSSL%\crypto\bio\bss_file.o
del %OPENSSL%\crypto\bio\bss_log.d
del %OPENSSL%\crypto\bio\bss_log.o
del %OPENSSL%\crypto\bio\bss_mem.d
del %OPENSSL%\crypto\bio\bss_mem.o
del %OPENSSL%\crypto\bio\bss_null.d
del %OPENSSL%\crypto\bio\bss_null.o
del %OPENSSL%\crypto\bio\bss_sock.d
del %OPENSSL%\crypto\bio\bss_sock.o
del %OPENSSL%\crypto\blake2\blake2b.d
del %OPENSSL%\crypto\blake2\blake2b.o
del %OPENSSL%\crypto\blake2\blake2s.d
del %OPENSSL%\crypto\blake2\blake2s.o
del %OPENSSL%\crypto\blake2\m_blake2b.d
del %OPENSSL%\crypto\blake2\m_blake2b.o
del %OPENSSL%\crypto\blake2\m_blake2s.d
del %OPENSSL%\crypto\blake2\m_blake2s.o
del %OPENSSL%\crypto\bn\bn-586.o
del %OPENSSL%\crypto\bn\bn-586.s
del %OPENSSL%\crypto\bn\bn_add.d
del %OPENSSL%\crypto\bn\bn_add.o
del %OPENSSL%\crypto\bn\bn_blind.d
del %OPENSSL%\crypto\bn\bn_blind.o
del %OPENSSL%\crypto\bn\bn_const.d
del %OPENSSL%\crypto\bn\bn_const.o
del %OPENSSL%\crypto\bn\bn_ctx.d
del %OPENSSL%\crypto\bn\bn_ctx.o
del %OPENSSL%\crypto\bn\bn_depr.d
del %OPENSSL%\crypto\bn\bn_depr.o
del %OPENSSL%\crypto\bn\bn_dh.d
del %OPENSSL%\crypto\bn\bn_dh.o
del %OPENSSL%\crypto\bn\bn_div.d
del %OPENSSL%\crypto\bn\bn_div.o
del %OPENSSL%\crypto\bn\bn_err.d
del %OPENSSL%\crypto\bn\bn_err.o
del %OPENSSL%\crypto\bn\bn_exp.d
del %OPENSSL%\crypto\bn\bn_exp.o
del %OPENSSL%\crypto\bn\bn_exp2.d
del %OPENSSL%\crypto\bn\bn_exp2.o
del %OPENSSL%\crypto\bn\bn_gcd.d
del %OPENSSL%\crypto\bn\bn_gcd.o
del %OPENSSL%\crypto\bn\bn_gf2m.d
del %OPENSSL%\crypto\bn\bn_gf2m.o
del %OPENSSL%\crypto\bn\bn_intern.d
del %OPENSSL%\crypto\bn\bn_intern.o
del %OPENSSL%\crypto\bn\bn_kron.d
del %OPENSSL%\crypto\bn\bn_kron.o
del %OPENSSL%\crypto\bn\bn_lib.d
del %OPENSSL%\crypto\bn\bn_lib.o
del %OPENSSL%\crypto\bn\bn_mod.d
del %OPENSSL%\crypto\bn\bn_mod.o
del %OPENSSL%\crypto\bn\bn_mont.d
del %OPENSSL%\crypto\bn\bn_mont.o
del %OPENSSL%\crypto\bn\bn_mpi.d
del %OPENSSL%\crypto\bn\bn_mpi.o
del %OPENSSL%\crypto\bn\bn_mul.d
del %OPENSSL%\crypto\bn\bn_mul.o
del %OPENSSL%\crypto\bn\bn_nist.d
del %OPENSSL%\crypto\bn\bn_nist.o
del %OPENSSL%\crypto\bn\bn_prime.d
del %OPENSSL%\crypto\bn\bn_prime.o
del %OPENSSL%\crypto\bn\bn_print.d
del %OPENSSL%\crypto\bn\bn_print.o
del %OPENSSL%\crypto\bn\bn_rand.d
del %OPENSSL%\crypto\bn\bn_rand.o
del %OPENSSL%\crypto\bn\bn_recp.d
del %OPENSSL%\crypto\bn\bn_recp.o
del %OPENSSL%\crypto\bn\bn_shift.d
del %OPENSSL%\crypto\bn\bn_shift.o
del %OPENSSL%\crypto\bn\bn_sqr.d
del %OPENSSL%\crypto\bn\bn_sqr.o
del %OPENSSL%\crypto\bn\bn_sqrt.d
del %OPENSSL%\crypto\bn\bn_sqrt.o
del %OPENSSL%\crypto\bn\bn_srp.d
del %OPENSSL%\crypto\bn\bn_srp.o
del %OPENSSL%\crypto\bn\bn_word.d
del %OPENSSL%\crypto\bn\bn_word.o
del %OPENSSL%\crypto\bn\bn_x931p.d
del %OPENSSL%\crypto\bn\bn_x931p.o
del %OPENSSL%\crypto\bn\co-586.o
del %OPENSSL%\crypto\bn\co-586.s
del %OPENSSL%\crypto\bn\x86-gf2m.o
del %OPENSSL%\crypto\bn\x86-gf2m.s
del %OPENSSL%\crypto\bn\x86-mont.o
del %OPENSSL%\crypto\bn\x86-mont.s
del %OPENSSL%\crypto\buffer\buf_err.d
del %OPENSSL%\crypto\buffer\buf_err.o
del %OPENSSL%\crypto\buffer\buffer.d
del %OPENSSL%\crypto\buffer\buffer.o
del %OPENSSL%\crypto\buildinf.h
del %OPENSSL%\crypto\camellia\cmll-x86.o
del %OPENSSL%\crypto\camellia\cmll-x86.s
del %OPENSSL%\crypto\camellia\cmll_cfb.d
del %OPENSSL%\crypto\camellia\cmll_cfb.o
del %OPENSSL%\crypto\camellia\cmll_ctr.d
del %OPENSSL%\crypto\camellia\cmll_ctr.o
del %OPENSSL%\crypto\camellia\cmll_ecb.d
del %OPENSSL%\crypto\camellia\cmll_ecb.o
del %OPENSSL%\crypto\camellia\cmll_ofb.d
del %OPENSSL%\crypto\camellia\cmll_ofb.o
del %OPENSSL%\crypto\cast\c_cfb64.d
del %OPENSSL%\crypto\cast\c_cfb64.o
del %OPENSSL%\crypto\cast\c_ecb.d
del %OPENSSL%\crypto\cast\c_ecb.o
del %OPENSSL%\crypto\cast\c_enc.d
del %OPENSSL%\crypto\cast\c_enc.o
del %OPENSSL%\crypto\cast\c_ofb64.d
del %OPENSSL%\crypto\cast\c_ofb64.o
del %OPENSSL%\crypto\cast\c_skey.d
del %OPENSSL%\crypto\cast\c_skey.o
del %OPENSSL%\crypto\chacha\chacha-x86.o
del %OPENSSL%\crypto\chacha\chacha-x86.s
del %OPENSSL%\crypto\cmac\cm_ameth.d
del %OPENSSL%\crypto\cmac\cm_ameth.o
del %OPENSSL%\crypto\cmac\cm_pmeth.d
del %OPENSSL%\crypto\cmac\cm_pmeth.o
del %OPENSSL%\crypto\cmac\cmac.d
del %OPENSSL%\crypto\cmac\cmac.o
del %OPENSSL%\crypto\cms\cms_asn1.d
del %OPENSSL%\crypto\cms\cms_asn1.o
del %OPENSSL%\crypto\cms\cms_att.d
del %OPENSSL%\crypto\cms\cms_att.o
del %OPENSSL%\crypto\cms\cms_cd.d
del %OPENSSL%\crypto\cms\cms_cd.o
del %OPENSSL%\crypto\cms\cms_dd.d
del %OPENSSL%\crypto\cms\cms_dd.o
del %OPENSSL%\crypto\cms\cms_enc.d
del %OPENSSL%\crypto\cms\cms_enc.o
del %OPENSSL%\crypto\cms\cms_env.d
del %OPENSSL%\crypto\cms\cms_env.o
del %OPENSSL%\crypto\cms\cms_err.d
del %OPENSSL%\crypto\cms\cms_err.o
del %OPENSSL%\crypto\cms\cms_ess.d
del %OPENSSL%\crypto\cms\cms_ess.o
del %OPENSSL%\crypto\cms\cms_io.d
del %OPENSSL%\crypto\cms\cms_io.o
del %OPENSSL%\crypto\cms\cms_kari.d
del %OPENSSL%\crypto\cms\cms_kari.o
del %OPENSSL%\crypto\cms\cms_lib.d
del %OPENSSL%\crypto\cms\cms_lib.o
del %OPENSSL%\crypto\cms\cms_pwri.d
del %OPENSSL%\crypto\cms\cms_pwri.o
del %OPENSSL%\crypto\cms\cms_sd.d
del %OPENSSL%\crypto\cms\cms_sd.o
del %OPENSSL%\crypto\cms\cms_smime.d
del %OPENSSL%\crypto\cms\cms_smime.o
del %OPENSSL%\crypto\comp\c_zlib.d
del %OPENSSL%\crypto\comp\c_zlib.o
del %OPENSSL%\crypto\comp\comp_err.d
del %OPENSSL%\crypto\comp\comp_err.o
del %OPENSSL%\crypto\comp\comp_lib.d
del %OPENSSL%\crypto\comp\comp_lib.o
del %OPENSSL%\crypto\conf\conf_api.d
del %OPENSSL%\crypto\conf\conf_api.o
del %OPENSSL%\crypto\conf\conf_def.d
del %OPENSSL%\crypto\conf\conf_def.o
del %OPENSSL%\crypto\conf\conf_err.d
del %OPENSSL%\crypto\conf\conf_err.o
del %OPENSSL%\crypto\conf\conf_lib.d
del %OPENSSL%\crypto\conf\conf_lib.o
del %OPENSSL%\crypto\conf\conf_mall.d
del %OPENSSL%\crypto\conf\conf_mall.o
del %OPENSSL%\crypto\conf\conf_mod.d
del %OPENSSL%\crypto\conf\conf_mod.o
del %OPENSSL%\crypto\conf\conf_sap.d
del %OPENSSL%\crypto\conf\conf_sap.o
del %OPENSSL%\crypto\conf\conf_ssl.d
del %OPENSSL%\crypto\conf\conf_ssl.o
del %OPENSSL%\crypto\cpt_err.d
del %OPENSSL%\crypto\cpt_err.o
del %OPENSSL%\crypto\cryptlib.d
del %OPENSSL%\crypto\cryptlib.o
del %OPENSSL%\crypto\ct\ct_b64.d
del %OPENSSL%\crypto\ct\ct_b64.o
del %OPENSSL%\crypto\ct\ct_err.d
del %OPENSSL%\crypto\ct\ct_err.o
del %OPENSSL%\crypto\ct\ct_log.d
del %OPENSSL%\crypto\ct\ct_log.o
del %OPENSSL%\crypto\ct\ct_oct.d
del %OPENSSL%\crypto\ct\ct_oct.o
del %OPENSSL%\crypto\ct\ct_policy.d
del %OPENSSL%\crypto\ct\ct_policy.o
del %OPENSSL%\crypto\ct\ct_prn.d
del %OPENSSL%\crypto\ct\ct_prn.o
del %OPENSSL%\crypto\ct\ct_sct.d
del %OPENSSL%\crypto\ct\ct_sct.o
del %OPENSSL%\crypto\ct\ct_sct_ctx.d
del %OPENSSL%\crypto\ct\ct_sct_ctx.o
del %OPENSSL%\crypto\ct\ct_vfy.d
del %OPENSSL%\crypto\ct\ct_vfy.o
del %OPENSSL%\crypto\ct\ct_x509v3.d
del %OPENSSL%\crypto\ct\ct_x509v3.o
del %OPENSSL%\crypto\ctype.d
del %OPENSSL%\crypto\ctype.o
del %OPENSSL%\crypto\cversion.d
del %OPENSSL%\crypto\cversion.o
del %OPENSSL%\crypto\des\cbc_cksm.d
del %OPENSSL%\crypto\des\cbc_cksm.o
del %OPENSSL%\crypto\des\cbc_enc.d
del %OPENSSL%\crypto\des\cbc_enc.o
del %OPENSSL%\crypto\des\cfb64ede.d
del %OPENSSL%\crypto\des\cfb64ede.o
del %OPENSSL%\crypto\des\cfb64enc.d
del %OPENSSL%\crypto\des\cfb64enc.o
del %OPENSSL%\crypto\des\cfb_enc.d
del %OPENSSL%\crypto\des\cfb_enc.o
del %OPENSSL%\crypto\des\crypt586.o
del %OPENSSL%\crypto\des\crypt586.s
del %OPENSSL%\crypto\des\des-586.o
del %OPENSSL%\crypto\des\des-586.s
del %OPENSSL%\crypto\des\ecb3_enc.d
del %OPENSSL%\crypto\des\ecb3_enc.o
del %OPENSSL%\crypto\des\ecb_enc.d
del %OPENSSL%\crypto\des\ecb_enc.o
del %OPENSSL%\crypto\des\fcrypt.d
del %OPENSSL%\crypto\des\fcrypt.o
del %OPENSSL%\crypto\des\ofb64ede.d
del %OPENSSL%\crypto\des\ofb64ede.o
del %OPENSSL%\crypto\des\ofb64enc.d
del %OPENSSL%\crypto\des\ofb64enc.o
del %OPENSSL%\crypto\des\ofb_enc.d
del %OPENSSL%\crypto\des\ofb_enc.o
del %OPENSSL%\crypto\des\pcbc_enc.d
del %OPENSSL%\crypto\des\pcbc_enc.o
del %OPENSSL%\crypto\des\qud_cksm.d
del %OPENSSL%\crypto\des\qud_cksm.o
del %OPENSSL%\crypto\des\rand_key.d
del %OPENSSL%\crypto\des\rand_key.o
del %OPENSSL%\crypto\des\set_key.d
del %OPENSSL%\crypto\des\set_key.o
del %OPENSSL%\crypto\des\str2key.d
del %OPENSSL%\crypto\des\str2key.o
del %OPENSSL%\crypto\des\xcbc_enc.d
del %OPENSSL%\crypto\des\xcbc_enc.o
del %OPENSSL%\crypto\dh\dh_ameth.d
del %OPENSSL%\crypto\dh\dh_ameth.o
del %OPENSSL%\crypto\dh\dh_asn1.d
del %OPENSSL%\crypto\dh\dh_asn1.o
del %OPENSSL%\crypto\dh\dh_check.d
del %OPENSSL%\crypto\dh\dh_check.o
del %OPENSSL%\crypto\dh\dh_depr.d
del %OPENSSL%\crypto\dh\dh_depr.o
del %OPENSSL%\crypto\dh\dh_err.d
del %OPENSSL%\crypto\dh\dh_err.o
del %OPENSSL%\crypto\dh\dh_gen.d
del %OPENSSL%\crypto\dh\dh_gen.o
del %OPENSSL%\crypto\dh\dh_kdf.d
del %OPENSSL%\crypto\dh\dh_kdf.o
del %OPENSSL%\crypto\dh\dh_key.d
del %OPENSSL%\crypto\dh\dh_key.o
del %OPENSSL%\crypto\dh\dh_lib.d
del %OPENSSL%\crypto\dh\dh_lib.o
del %OPENSSL%\crypto\dh\dh_meth.d
del %OPENSSL%\crypto\dh\dh_meth.o
del %OPENSSL%\crypto\dh\dh_pmeth.d
del %OPENSSL%\crypto\dh\dh_pmeth.o
del %OPENSSL%\crypto\dh\dh_prn.d
del %OPENSSL%\crypto\dh\dh_prn.o
del %OPENSSL%\crypto\dh\dh_rfc5114.d
del %OPENSSL%\crypto\dh\dh_rfc5114.o
del %OPENSSL%\crypto\dh\dh_rfc7919.d
del %OPENSSL%\crypto\dh\dh_rfc7919.o
del %OPENSSL%\crypto\dllmain.d
del %OPENSSL%\crypto\dllmain.o
del %OPENSSL%\crypto\dsa\dsa_ameth.d
del %OPENSSL%\crypto\dsa\dsa_ameth.o
del %OPENSSL%\crypto\dsa\dsa_asn1.d
del %OPENSSL%\crypto\dsa\dsa_asn1.o
del %OPENSSL%\crypto\dsa\dsa_depr.d
del %OPENSSL%\crypto\dsa\dsa_depr.o
del %OPENSSL%\crypto\dsa\dsa_err.d
del %OPENSSL%\crypto\dsa\dsa_err.o
del %OPENSSL%\crypto\dsa\dsa_gen.d
del %OPENSSL%\crypto\dsa\dsa_gen.o
del %OPENSSL%\crypto\dsa\dsa_key.d
del %OPENSSL%\crypto\dsa\dsa_key.o
del %OPENSSL%\crypto\dsa\dsa_lib.d
del %OPENSSL%\crypto\dsa\dsa_lib.o
del %OPENSSL%\crypto\dsa\dsa_meth.d
del %OPENSSL%\crypto\dsa\dsa_meth.o
del %OPENSSL%\crypto\dsa\dsa_ossl.d
del %OPENSSL%\crypto\dsa\dsa_ossl.o
del %OPENSSL%\crypto\dsa\dsa_pmeth.d
del %OPENSSL%\crypto\dsa\dsa_pmeth.o
del %OPENSSL%\crypto\dsa\dsa_prn.d
del %OPENSSL%\crypto\dsa\dsa_prn.o
del %OPENSSL%\crypto\dsa\dsa_sign.d
del %OPENSSL%\crypto\dsa\dsa_sign.o
del %OPENSSL%\crypto\dsa\dsa_vrf.d
del %OPENSSL%\crypto\dsa\dsa_vrf.o
del %OPENSSL%\crypto\dso\dso_dl.d
del %OPENSSL%\crypto\dso\dso_dl.o
del %OPENSSL%\crypto\dso\dso_dlfcn.d
del %OPENSSL%\crypto\dso\dso_dlfcn.o
del %OPENSSL%\crypto\dso\dso_err.d
del %OPENSSL%\crypto\dso\dso_err.o
del %OPENSSL%\crypto\dso\dso_lib.d
del %OPENSSL%\crypto\dso\dso_lib.o
del %OPENSSL%\crypto\dso\dso_openssl.d
del %OPENSSL%\crypto\dso\dso_openssl.o
del %OPENSSL%\crypto\dso\dso_vms.d
del %OPENSSL%\crypto\dso\dso_vms.o
del %OPENSSL%\crypto\dso\dso_win32.d
del %OPENSSL%\crypto\dso\dso_win32.o
del %OPENSSL%\crypto\ebcdic.d
del %OPENSSL%\crypto\ebcdic.o
del %OPENSSL%\crypto\ec\curve25519.d
del %OPENSSL%\crypto\ec\curve25519.o
del %OPENSSL%\crypto\ec\curve448\arch_32\f_impl.d
del %OPENSSL%\crypto\ec\curve448\arch_32\f_impl.o
del %OPENSSL%\crypto\ec\curve448\curve448.d
del %OPENSSL%\crypto\ec\curve448\curve448.o
del %OPENSSL%\crypto\ec\curve448\curve448_tables.d
del %OPENSSL%\crypto\ec\curve448\curve448_tables.o
del %OPENSSL%\crypto\ec\curve448\eddsa.d
del %OPENSSL%\crypto\ec\curve448\eddsa.o
del %OPENSSL%\crypto\ec\curve448\f_generic.d
del %OPENSSL%\crypto\ec\curve448\f_generic.o
del %OPENSSL%\crypto\ec\curve448\scalar.d
del %OPENSSL%\crypto\ec\curve448\scalar.o
del %OPENSSL%\crypto\ec\ec2_oct.d
del %OPENSSL%\crypto\ec\ec2_oct.o
del %OPENSSL%\crypto\ec\ec2_smpl.d
del %OPENSSL%\crypto\ec\ec2_smpl.o
del %OPENSSL%\crypto\ec\ec_ameth.d
del %OPENSSL%\crypto\ec\ec_ameth.o
del %OPENSSL%\crypto\ec\ec_asn1.d
del %OPENSSL%\crypto\ec\ec_asn1.o
del %OPENSSL%\crypto\ec\ec_check.d
del %OPENSSL%\crypto\ec\ec_check.o
del %OPENSSL%\crypto\ec\ec_curve.d
del %OPENSSL%\crypto\ec\ec_curve.o
del %OPENSSL%\crypto\ec\ec_cvt.d
del %OPENSSL%\crypto\ec\ec_cvt.o
del %OPENSSL%\crypto\ec\ec_err.d
del %OPENSSL%\crypto\ec\ec_err.o
del %OPENSSL%\crypto\ec\ec_key.d
del %OPENSSL%\crypto\ec\ec_key.o
del %OPENSSL%\crypto\ec\ec_kmeth.d
del %OPENSSL%\crypto\ec\ec_kmeth.o
del %OPENSSL%\crypto\ec\ec_lib.d
del %OPENSSL%\crypto\ec\ec_lib.o
del %OPENSSL%\crypto\ec\ec_mult.d
del %OPENSSL%\crypto\ec\ec_mult.o
del %OPENSSL%\crypto\ec\ec_oct.d
del %OPENSSL%\crypto\ec\ec_oct.o
del %OPENSSL%\crypto\ec\ec_pmeth.d
del %OPENSSL%\crypto\ec\ec_pmeth.o
del %OPENSSL%\crypto\ec\ec_print.d
del %OPENSSL%\crypto\ec\ec_print.o
del %OPENSSL%\crypto\ec\ecdh_kdf.d
del %OPENSSL%\crypto\ec\ecdh_kdf.o
del %OPENSSL%\crypto\ec\ecdh_ossl.d
del %OPENSSL%\crypto\ec\ecdh_ossl.o
del %OPENSSL%\crypto\ec\ecdsa_ossl.d
del %OPENSSL%\crypto\ec\ecdsa_ossl.o
del %OPENSSL%\crypto\ec\ecdsa_sign.d
del %OPENSSL%\crypto\ec\ecdsa_sign.o
del %OPENSSL%\crypto\ec\ecdsa_vrf.d
del %OPENSSL%\crypto\ec\ecdsa_vrf.o
del %OPENSSL%\crypto\ec\eck_prn.d
del %OPENSSL%\crypto\ec\eck_prn.o
del %OPENSSL%\crypto\ec\ecp_mont.d
del %OPENSSL%\crypto\ec\ecp_mont.o
del %OPENSSL%\crypto\ec\ecp_nist.d
del %OPENSSL%\crypto\ec\ecp_nist.o
del %OPENSSL%\crypto\ec\ecp_nistp224.d
del %OPENSSL%\crypto\ec\ecp_nistp224.o
del %OPENSSL%\crypto\ec\ecp_nistp256.d
del %OPENSSL%\crypto\ec\ecp_nistp256.o
del %OPENSSL%\crypto\ec\ecp_nistp521.d
del %OPENSSL%\crypto\ec\ecp_nistp521.o
del %OPENSSL%\crypto\ec\ecp_nistputil.d
del %OPENSSL%\crypto\ec\ecp_nistputil.o
del %OPENSSL%\crypto\ec\ecp_nistz256-x86.o
del %OPENSSL%\crypto\ec\ecp_nistz256-x86.s
del %OPENSSL%\crypto\ec\ecp_nistz256.d
del %OPENSSL%\crypto\ec\ecp_nistz256.o
del %OPENSSL%\crypto\ec\ecp_oct.d
del %OPENSSL%\crypto\ec\ecp_oct.o
del %OPENSSL%\crypto\ec\ecp_smpl.d
del %OPENSSL%\crypto\ec\ecp_smpl.o
del %OPENSSL%\crypto\ec\ecx_meth.d
del %OPENSSL%\crypto\ec\ecx_meth.o
del %OPENSSL%\crypto\engine\eng_all.d
del %OPENSSL%\crypto\engine\eng_all.o
del %OPENSSL%\crypto\engine\eng_cnf.d
del %OPENSSL%\crypto\engine\eng_cnf.o
del %OPENSSL%\crypto\engine\eng_ctrl.d
del %OPENSSL%\crypto\engine\eng_ctrl.o
del %OPENSSL%\crypto\engine\eng_dyn.d
del %OPENSSL%\crypto\engine\eng_dyn.o
del %OPENSSL%\crypto\engine\eng_err.d
del %OPENSSL%\crypto\engine\eng_err.o
del %OPENSSL%\crypto\engine\eng_fat.d
del %OPENSSL%\crypto\engine\eng_fat.o
del %OPENSSL%\crypto\engine\eng_init.d
del %OPENSSL%\crypto\engine\eng_init.o
del %OPENSSL%\crypto\engine\eng_lib.d
del %OPENSSL%\crypto\engine\eng_lib.o
del %OPENSSL%\crypto\engine\eng_list.d
del %OPENSSL%\crypto\engine\eng_list.o
del %OPENSSL%\crypto\engine\eng_openssl.d
del %OPENSSL%\crypto\engine\eng_openssl.o
del %OPENSSL%\crypto\engine\eng_pkey.d
del %OPENSSL%\crypto\engine\eng_pkey.o
del %OPENSSL%\crypto\engine\eng_rdrand.d
del %OPENSSL%\crypto\engine\eng_rdrand.o
del %OPENSSL%\crypto\engine\eng_table.d
del %OPENSSL%\crypto\engine\eng_table.o
del %OPENSSL%\crypto\engine\tb_asnmth.d
del %OPENSSL%\crypto\engine\tb_asnmth.o
del %OPENSSL%\crypto\engine\tb_cipher.d
del %OPENSSL%\crypto\engine\tb_cipher.o
del %OPENSSL%\crypto\engine\tb_dh.d
del %OPENSSL%\crypto\engine\tb_dh.o
del %OPENSSL%\crypto\engine\tb_digest.d
del %OPENSSL%\crypto\engine\tb_digest.o
del %OPENSSL%\crypto\engine\tb_dsa.d
del %OPENSSL%\crypto\engine\tb_dsa.o
del %OPENSSL%\crypto\engine\tb_eckey.d
del %OPENSSL%\crypto\engine\tb_eckey.o
del %OPENSSL%\crypto\engine\tb_pkmeth.d
del %OPENSSL%\crypto\engine\tb_pkmeth.o
del %OPENSSL%\crypto\engine\tb_rand.d
del %OPENSSL%\crypto\engine\tb_rand.o
del %OPENSSL%\crypto\engine\tb_rsa.d
del %OPENSSL%\crypto\engine\tb_rsa.o
del %OPENSSL%\crypto\err\err.d
del %OPENSSL%\crypto\err\err.o
del %OPENSSL%\crypto\err\err_all.d
del %OPENSSL%\crypto\err\err_all.o
del %OPENSSL%\crypto\err\err_prn.d
del %OPENSSL%\crypto\err\err_prn.o
del %OPENSSL%\crypto\evp\bio_b64.d
del %OPENSSL%\crypto\evp\bio_b64.o
del %OPENSSL%\crypto\evp\bio_enc.d
del %OPENSSL%\crypto\evp\bio_enc.o
del %OPENSSL%\crypto\evp\bio_md.d
del %OPENSSL%\crypto\evp\bio_md.o
del %OPENSSL%\crypto\evp\bio_ok.d
del %OPENSSL%\crypto\evp\bio_ok.o
del %OPENSSL%\crypto\evp\c_allc.d
del %OPENSSL%\crypto\evp\c_allc.o
del %OPENSSL%\crypto\evp\c_alld.d
del %OPENSSL%\crypto\evp\c_alld.o
del %OPENSSL%\crypto\evp\cmeth_lib.d
del %OPENSSL%\crypto\evp\cmeth_lib.o
del %OPENSSL%\crypto\evp\digest.d
del %OPENSSL%\crypto\evp\digest.o
del %OPENSSL%\crypto\evp\e_aes.d
del %OPENSSL%\crypto\evp\e_aes.o
del %OPENSSL%\crypto\evp\e_aes_cbc_hmac_sha1.d
del %OPENSSL%\crypto\evp\e_aes_cbc_hmac_sha1.o
del %OPENSSL%\crypto\evp\e_aes_cbc_hmac_sha256.d
del %OPENSSL%\crypto\evp\e_aes_cbc_hmac_sha256.o
del %OPENSSL%\crypto\evp\e_aria.d
del %OPENSSL%\crypto\evp\e_aria.o
del %OPENSSL%\crypto\evp\e_bf.d
del %OPENSSL%\crypto\evp\e_bf.o
del %OPENSSL%\crypto\evp\e_camellia.d
del %OPENSSL%\crypto\evp\e_camellia.o
del %OPENSSL%\crypto\evp\e_cast.d
del %OPENSSL%\crypto\evp\e_cast.o
del %OPENSSL%\crypto\evp\e_chacha20_poly1305.d
del %OPENSSL%\crypto\evp\e_chacha20_poly1305.o
del %OPENSSL%\crypto\evp\e_des.d
del %OPENSSL%\crypto\evp\e_des.o
del %OPENSSL%\crypto\evp\e_des3.d
del %OPENSSL%\crypto\evp\e_des3.o
del %OPENSSL%\crypto\evp\e_idea.d
del %OPENSSL%\crypto\evp\e_idea.o
del %OPENSSL%\crypto\evp\e_null.d
del %OPENSSL%\crypto\evp\e_null.o
del %OPENSSL%\crypto\evp\e_old.d
del %OPENSSL%\crypto\evp\e_old.o
del %OPENSSL%\crypto\evp\e_rc2.d
del %OPENSSL%\crypto\evp\e_rc2.o
del %OPENSSL%\crypto\evp\e_rc4.d
del %OPENSSL%\crypto\evp\e_rc4.o
del %OPENSSL%\crypto\evp\e_rc4_hmac_md5.d
del %OPENSSL%\crypto\evp\e_rc4_hmac_md5.o
del %OPENSSL%\crypto\evp\e_rc5.d
del %OPENSSL%\crypto\evp\e_rc5.o
del %OPENSSL%\crypto\evp\e_seed.d
del %OPENSSL%\crypto\evp\e_seed.o
del %OPENSSL%\crypto\evp\e_sm4.d
del %OPENSSL%\crypto\evp\e_sm4.o
del %OPENSSL%\crypto\evp\e_xcbc_d.d
del %OPENSSL%\crypto\evp\e_xcbc_d.o
del %OPENSSL%\crypto\evp\encode.d
del %OPENSSL%\crypto\evp\encode.o
del %OPENSSL%\crypto\evp\evp_cnf.d
del %OPENSSL%\crypto\evp\evp_cnf.o
del %OPENSSL%\crypto\evp\evp_enc.d
del %OPENSSL%\crypto\evp\evp_enc.o
del %OPENSSL%\crypto\evp\evp_err.d
del %OPENSSL%\crypto\evp\evp_err.o
del %OPENSSL%\crypto\evp\evp_key.d
del %OPENSSL%\crypto\evp\evp_key.o
del %OPENSSL%\crypto\evp\evp_lib.d
del %OPENSSL%\crypto\evp\evp_lib.o
del %OPENSSL%\crypto\evp\evp_pbe.d
del %OPENSSL%\crypto\evp\evp_pbe.o
del %OPENSSL%\crypto\evp\evp_pkey.d
del %OPENSSL%\crypto\evp\evp_pkey.o
del %OPENSSL%\crypto\evp\m_md2.d
del %OPENSSL%\crypto\evp\m_md2.o
del %OPENSSL%\crypto\evp\m_md4.d
del %OPENSSL%\crypto\evp\m_md4.o
del %OPENSSL%\crypto\evp\m_md5.d
del %OPENSSL%\crypto\evp\m_md5.o
del %OPENSSL%\crypto\evp\m_md5_sha1.d
del %OPENSSL%\crypto\evp\m_md5_sha1.o
del %OPENSSL%\crypto\evp\m_mdc2.d
del %OPENSSL%\crypto\evp\m_mdc2.o
del %OPENSSL%\crypto\evp\m_null.d
del %OPENSSL%\crypto\evp\m_null.o
del %OPENSSL%\crypto\evp\m_ripemd.d
del %OPENSSL%\crypto\evp\m_ripemd.o
del %OPENSSL%\crypto\evp\m_sha1.d
del %OPENSSL%\crypto\evp\m_sha1.o
del %OPENSSL%\crypto\evp\m_sha3.d
del %OPENSSL%\crypto\evp\m_sha3.o
del %OPENSSL%\crypto\evp\m_sigver.d
del %OPENSSL%\crypto\evp\m_sigver.o
del %OPENSSL%\crypto\evp\m_wp.d
del %OPENSSL%\crypto\evp\m_wp.o
del %OPENSSL%\crypto\evp\names.d
del %OPENSSL%\crypto\evp\names.o
del %OPENSSL%\crypto\evp\p5_crpt.d
del %OPENSSL%\crypto\evp\p5_crpt.o
del %OPENSSL%\crypto\evp\p5_crpt2.d
del %OPENSSL%\crypto\evp\p5_crpt2.o
del %OPENSSL%\crypto\evp\p_dec.d
del %OPENSSL%\crypto\evp\p_dec.o
del %OPENSSL%\crypto\evp\p_enc.d
del %OPENSSL%\crypto\evp\p_enc.o
del %OPENSSL%\crypto\evp\p_lib.d
del %OPENSSL%\crypto\evp\p_lib.o
del %OPENSSL%\crypto\evp\p_open.d
del %OPENSSL%\crypto\evp\p_open.o
del %OPENSSL%\crypto\evp\p_seal.d
del %OPENSSL%\crypto\evp\p_seal.o
del %OPENSSL%\crypto\evp\p_sign.d
del %OPENSSL%\crypto\evp\p_sign.o
del %OPENSSL%\crypto\evp\p_verify.d
del %OPENSSL%\crypto\evp\p_verify.o
del %OPENSSL%\crypto\evp\pbe_scrypt.d
del %OPENSSL%\crypto\evp\pbe_scrypt.o
del %OPENSSL%\crypto\evp\pmeth_fn.d
del %OPENSSL%\crypto\evp\pmeth_fn.o
del %OPENSSL%\crypto\evp\pmeth_gn.d
del %OPENSSL%\crypto\evp\pmeth_gn.o
del %OPENSSL%\crypto\evp\pmeth_lib.d
del %OPENSSL%\crypto\evp\pmeth_lib.o
del %OPENSSL%\crypto\ex_data.d
del %OPENSSL%\crypto\ex_data.o
del %OPENSSL%\crypto\getenv.d
del %OPENSSL%\crypto\getenv.o
del %OPENSSL%\crypto\hmac\hm_ameth.d
del %OPENSSL%\crypto\hmac\hm_ameth.o
del %OPENSSL%\crypto\hmac\hm_pmeth.d
del %OPENSSL%\crypto\hmac\hm_pmeth.o
del %OPENSSL%\crypto\hmac\hmac.d
del %OPENSSL%\crypto\hmac\hmac.o
del %OPENSSL%\crypto\idea\i_cbc.d
del %OPENSSL%\crypto\idea\i_cbc.o
del %OPENSSL%\crypto\idea\i_cfb64.d
del %OPENSSL%\crypto\idea\i_cfb64.o
del %OPENSSL%\crypto\idea\i_ecb.d
del %OPENSSL%\crypto\idea\i_ecb.o
del %OPENSSL%\crypto\idea\i_ofb64.d
del %OPENSSL%\crypto\idea\i_ofb64.o
del %OPENSSL%\crypto\idea\i_skey.d
del %OPENSSL%\crypto\idea\i_skey.o
del %OPENSSL%\crypto\init.d
del %OPENSSL%\crypto\init.o
del %OPENSSL%\crypto\kdf\hkdf.d
del %OPENSSL%\crypto\kdf\hkdf.o
del %OPENSSL%\crypto\kdf\kdf_err.d
del %OPENSSL%\crypto\kdf\kdf_err.o
del %OPENSSL%\crypto\kdf\scrypt.d
del %OPENSSL%\crypto\kdf\scrypt.o
del %OPENSSL%\crypto\kdf\tls1_prf.d
del %OPENSSL%\crypto\kdf\tls1_prf.o
del %OPENSSL%\crypto\lhash\lh_stats.d
del %OPENSSL%\crypto\lhash\lh_stats.o
del %OPENSSL%\crypto\lhash\lhash.d
del %OPENSSL%\crypto\lhash\lhash.o
del %OPENSSL%\crypto\md4\md4_dgst.d
del %OPENSSL%\crypto\md4\md4_dgst.o
del %OPENSSL%\crypto\md4\md4_one.d
del %OPENSSL%\crypto\md4\md4_one.o
del %OPENSSL%\crypto\md5\md5-586.o
del %OPENSSL%\crypto\md5\md5-586.s
del %OPENSSL%\crypto\md5\md5_dgst.d
del %OPENSSL%\crypto\md5\md5_dgst.o
del %OPENSSL%\crypto\md5\md5_one.d
del %OPENSSL%\crypto\md5\md5_one.o
del %OPENSSL%\crypto\mdc2\mdc2_one.d
del %OPENSSL%\crypto\mdc2\mdc2_one.o
del %OPENSSL%\crypto\mdc2\mdc2dgst.d
del %OPENSSL%\crypto\mdc2\mdc2dgst.o
del %OPENSSL%\crypto\mem.d
del %OPENSSL%\crypto\mem.o
del %OPENSSL%\crypto\mem_dbg.d
del %OPENSSL%\crypto\mem_dbg.o
del %OPENSSL%\crypto\mem_sec.d
del %OPENSSL%\crypto\mem_sec.o
del %OPENSSL%\crypto\modes\cbc128.d
del %OPENSSL%\crypto\modes\cbc128.o
del %OPENSSL%\crypto\modes\ccm128.d
del %OPENSSL%\crypto\modes\ccm128.o
del %OPENSSL%\crypto\modes\cfb128.d
del %OPENSSL%\crypto\modes\cfb128.o
del %OPENSSL%\crypto\modes\ctr128.d
del %OPENSSL%\crypto\modes\ctr128.o
del %OPENSSL%\crypto\modes\cts128.d
del %OPENSSL%\crypto\modes\cts128.o
del %OPENSSL%\crypto\modes\gcm128.d
del %OPENSSL%\crypto\modes\gcm128.o
del %OPENSSL%\crypto\modes\ghash-x86.o
del %OPENSSL%\crypto\modes\ghash-x86.s
del %OPENSSL%\crypto\modes\ocb128.d
del %OPENSSL%\crypto\modes\ocb128.o
del %OPENSSL%\crypto\modes\ofb128.d
del %OPENSSL%\crypto\modes\ofb128.o
del %OPENSSL%\crypto\modes\wrap128.d
del %OPENSSL%\crypto\modes\wrap128.o
del %OPENSSL%\crypto\modes\xts128.d
del %OPENSSL%\crypto\modes\xts128.o
del %OPENSSL%\crypto\o_dir.d
del %OPENSSL%\crypto\o_dir.o
del %OPENSSL%\crypto\o_fips.d
del %OPENSSL%\crypto\o_fips.o
del %OPENSSL%\crypto\o_fopen.d
del %OPENSSL%\crypto\o_fopen.o
del %OPENSSL%\crypto\o_init.d
del %OPENSSL%\crypto\o_init.o
del %OPENSSL%\crypto\o_str.d
del %OPENSSL%\crypto\o_str.o
del %OPENSSL%\crypto\o_time.d
del %OPENSSL%\crypto\o_time.o
del %OPENSSL%\crypto\objects\o_names.d
del %OPENSSL%\crypto\objects\o_names.o
del %OPENSSL%\crypto\objects\obj_dat.d
del %OPENSSL%\crypto\objects\obj_dat.o
del %OPENSSL%\crypto\objects\obj_err.d
del %OPENSSL%\crypto\objects\obj_err.o
del %OPENSSL%\crypto\objects\obj_lib.d
del %OPENSSL%\crypto\objects\obj_lib.o
del %OPENSSL%\crypto\objects\obj_xref.d
del %OPENSSL%\crypto\objects\obj_xref.o
del %OPENSSL%\crypto\ocsp\ocsp_asn.d
del %OPENSSL%\crypto\ocsp\ocsp_asn.o
del %OPENSSL%\crypto\ocsp\ocsp_cl.d
del %OPENSSL%\crypto\ocsp\ocsp_cl.o
del %OPENSSL%\crypto\ocsp\ocsp_err.d
del %OPENSSL%\crypto\ocsp\ocsp_err.o
del %OPENSSL%\crypto\ocsp\ocsp_ext.d
del %OPENSSL%\crypto\ocsp\ocsp_ext.o
del %OPENSSL%\crypto\ocsp\ocsp_ht.d
del %OPENSSL%\crypto\ocsp\ocsp_ht.o
del %OPENSSL%\crypto\ocsp\ocsp_lib.d
del %OPENSSL%\crypto\ocsp\ocsp_lib.o
del %OPENSSL%\crypto\ocsp\ocsp_prn.d
del %OPENSSL%\crypto\ocsp\ocsp_prn.o
del %OPENSSL%\crypto\ocsp\ocsp_srv.d
del %OPENSSL%\crypto\ocsp\ocsp_srv.o
del %OPENSSL%\crypto\ocsp\ocsp_vfy.d
del %OPENSSL%\crypto\ocsp\ocsp_vfy.o
del %OPENSSL%\crypto\ocsp\v3_ocsp.d
del %OPENSSL%\crypto\ocsp\v3_ocsp.o
del %OPENSSL%\crypto\pem\pem_all.d
del %OPENSSL%\crypto\pem\pem_all.o
del %OPENSSL%\crypto\pem\pem_err.d
del %OPENSSL%\crypto\pem\pem_err.o
del %OPENSSL%\crypto\pem\pem_info.d
del %OPENSSL%\crypto\pem\pem_info.o
del %OPENSSL%\crypto\pem\pem_lib.d
del %OPENSSL%\crypto\pem\pem_lib.o
del %OPENSSL%\crypto\pem\pem_oth.d
del %OPENSSL%\crypto\pem\pem_oth.o
del %OPENSSL%\crypto\pem\pem_pk8.d
del %OPENSSL%\crypto\pem\pem_pk8.o
del %OPENSSL%\crypto\pem\pem_pkey.d
del %OPENSSL%\crypto\pem\pem_pkey.o
del %OPENSSL%\crypto\pem\pem_sign.d
del %OPENSSL%\crypto\pem\pem_sign.o
del %OPENSSL%\crypto\pem\pem_x509.d
del %OPENSSL%\crypto\pem\pem_x509.o
del %OPENSSL%\crypto\pem\pem_xaux.d
del %OPENSSL%\crypto\pem\pem_xaux.o
del %OPENSSL%\crypto\pem\pvkfmt.d
del %OPENSSL%\crypto\pem\pvkfmt.o
del %OPENSSL%\crypto\pkcs12\p12_add.d
del %OPENSSL%\crypto\pkcs12\p12_add.o
del %OPENSSL%\crypto\pkcs12\p12_asn.d
del %OPENSSL%\crypto\pkcs12\p12_asn.o
del %OPENSSL%\crypto\pkcs12\p12_attr.d
del %OPENSSL%\crypto\pkcs12\p12_attr.o
del %OPENSSL%\crypto\pkcs12\p12_crpt.d
del %OPENSSL%\crypto\pkcs12\p12_crpt.o
del %OPENSSL%\crypto\pkcs12\p12_crt.d
del %OPENSSL%\crypto\pkcs12\p12_crt.o
del %OPENSSL%\crypto\pkcs12\p12_decr.d
del %OPENSSL%\crypto\pkcs12\p12_decr.o
del %OPENSSL%\crypto\pkcs12\p12_init.d
del %OPENSSL%\crypto\pkcs12\p12_init.o
del %OPENSSL%\crypto\pkcs12\p12_key.d
del %OPENSSL%\crypto\pkcs12\p12_key.o
del %OPENSSL%\crypto\pkcs12\p12_kiss.d
del %OPENSSL%\crypto\pkcs12\p12_kiss.o
del %OPENSSL%\crypto\pkcs12\p12_mutl.d
del %OPENSSL%\crypto\pkcs12\p12_mutl.o
del %OPENSSL%\crypto\pkcs12\p12_npas.d
del %OPENSSL%\crypto\pkcs12\p12_npas.o
del %OPENSSL%\crypto\pkcs12\p12_p8d.d
del %OPENSSL%\crypto\pkcs12\p12_p8d.o
del %OPENSSL%\crypto\pkcs12\p12_p8e.d
del %OPENSSL%\crypto\pkcs12\p12_p8e.o
del %OPENSSL%\crypto\pkcs12\p12_sbag.d
del %OPENSSL%\crypto\pkcs12\p12_sbag.o
del %OPENSSL%\crypto\pkcs12\p12_utl.d
del %OPENSSL%\crypto\pkcs12\p12_utl.o
del %OPENSSL%\crypto\pkcs12\pk12err.d
del %OPENSSL%\crypto\pkcs12\pk12err.o
del %OPENSSL%\crypto\pkcs7\bio_pk7.d
del %OPENSSL%\crypto\pkcs7\bio_pk7.o
del %OPENSSL%\crypto\pkcs7\pk7_asn1.d
del %OPENSSL%\crypto\pkcs7\pk7_asn1.o
del %OPENSSL%\crypto\pkcs7\pk7_attr.d
del %OPENSSL%\crypto\pkcs7\pk7_attr.o
del %OPENSSL%\crypto\pkcs7\pk7_doit.d
del %OPENSSL%\crypto\pkcs7\pk7_doit.o
del %OPENSSL%\crypto\pkcs7\pk7_lib.d
del %OPENSSL%\crypto\pkcs7\pk7_lib.o
del %OPENSSL%\crypto\pkcs7\pk7_mime.d
del %OPENSSL%\crypto\pkcs7\pk7_mime.o
del %OPENSSL%\crypto\pkcs7\pk7_smime.d
del %OPENSSL%\crypto\pkcs7\pk7_smime.o
del %OPENSSL%\crypto\pkcs7\pkcs7err.d
del %OPENSSL%\crypto\pkcs7\pkcs7err.o
del %OPENSSL%\crypto\poly1305\poly1305-x86.o
del %OPENSSL%\crypto\poly1305\poly1305-x86.s
del %OPENSSL%\crypto\poly1305\poly1305.d
del %OPENSSL%\crypto\poly1305\poly1305.o
del %OPENSSL%\crypto\poly1305\poly1305_ameth.d
del %OPENSSL%\crypto\poly1305\poly1305_ameth.o
del %OPENSSL%\crypto\poly1305\poly1305_pmeth.d
del %OPENSSL%\crypto\poly1305\poly1305_pmeth.o
del %OPENSSL%\crypto\rand\drbg_ctr.d
del %OPENSSL%\crypto\rand\drbg_ctr.o
del %OPENSSL%\crypto\rand\drbg_lib.d
del %OPENSSL%\crypto\rand\drbg_lib.o
del %OPENSSL%\crypto\rand\rand_egd.d
del %OPENSSL%\crypto\rand\rand_egd.o
del %OPENSSL%\crypto\rand\rand_err.d
del %OPENSSL%\crypto\rand\rand_err.o
del %OPENSSL%\crypto\rand\rand_lib.d
del %OPENSSL%\crypto\rand\rand_lib.o
del %OPENSSL%\crypto\rand\rand_unix.d
del %OPENSSL%\crypto\rand\rand_unix.o
del %OPENSSL%\crypto\rand\rand_vms.d
del %OPENSSL%\crypto\rand\rand_vms.o
del %OPENSSL%\crypto\rand\rand_win.d
del %OPENSSL%\crypto\rand\rand_win.o
del %OPENSSL%\crypto\rand\randfile.d
del %OPENSSL%\crypto\rand\randfile.o
del %OPENSSL%\crypto\rc2\rc2_cbc.d
del %OPENSSL%\crypto\rc2\rc2_cbc.o
del %OPENSSL%\crypto\rc2\rc2_ecb.d
del %OPENSSL%\crypto\rc2\rc2_ecb.o
del %OPENSSL%\crypto\rc2\rc2_skey.d
del %OPENSSL%\crypto\rc2\rc2_skey.o
del %OPENSSL%\crypto\rc2\rc2cfb64.d
del %OPENSSL%\crypto\rc2\rc2cfb64.o
del %OPENSSL%\crypto\rc2\rc2ofb64.d
del %OPENSSL%\crypto\rc2\rc2ofb64.o
del %OPENSSL%\crypto\rc4\rc4-586.o
del %OPENSSL%\crypto\rc4\rc4-586.s
del %OPENSSL%\crypto\ripemd\rmd-586.o
del %OPENSSL%\crypto\ripemd\rmd-586.s
del %OPENSSL%\crypto\ripemd\rmd_dgst.d
del %OPENSSL%\crypto\ripemd\rmd_dgst.o
del %OPENSSL%\crypto\ripemd\rmd_one.d
del %OPENSSL%\crypto\ripemd\rmd_one.o
del %OPENSSL%\crypto\rsa\rsa_ameth.d
del %OPENSSL%\crypto\rsa\rsa_ameth.o
del %OPENSSL%\crypto\rsa\rsa_asn1.d
del %OPENSSL%\crypto\rsa\rsa_asn1.o
del %OPENSSL%\crypto\rsa\rsa_chk.d
del %OPENSSL%\crypto\rsa\rsa_chk.o
del %OPENSSL%\crypto\rsa\rsa_crpt.d
del %OPENSSL%\crypto\rsa\rsa_crpt.o
del %OPENSSL%\crypto\rsa\rsa_depr.d
del %OPENSSL%\crypto\rsa\rsa_depr.o
del %OPENSSL%\crypto\rsa\rsa_err.d
del %OPENSSL%\crypto\rsa\rsa_err.o
del %OPENSSL%\crypto\rsa\rsa_gen.d
del %OPENSSL%\crypto\rsa\rsa_gen.o
del %OPENSSL%\crypto\rsa\rsa_lib.d
del %OPENSSL%\crypto\rsa\rsa_lib.o
del %OPENSSL%\crypto\rsa\rsa_meth.d
del %OPENSSL%\crypto\rsa\rsa_meth.o
del %OPENSSL%\crypto\rsa\rsa_mp.d
del %OPENSSL%\crypto\rsa\rsa_mp.o
del %OPENSSL%\crypto\rsa\rsa_none.d
del %OPENSSL%\crypto\rsa\rsa_none.o
del %OPENSSL%\crypto\rsa\rsa_oaep.d
del %OPENSSL%\crypto\rsa\rsa_oaep.o
del %OPENSSL%\crypto\rsa\rsa_ossl.d
del %OPENSSL%\crypto\rsa\rsa_ossl.o
del %OPENSSL%\crypto\rsa\rsa_pk1.d
del %OPENSSL%\crypto\rsa\rsa_pk1.o
del %OPENSSL%\crypto\rsa\rsa_pmeth.d
del %OPENSSL%\crypto\rsa\rsa_pmeth.o
del %OPENSSL%\crypto\rsa\rsa_prn.d
del %OPENSSL%\crypto\rsa\rsa_prn.o
del %OPENSSL%\crypto\rsa\rsa_pss.d
del %OPENSSL%\crypto\rsa\rsa_pss.o
del %OPENSSL%\crypto\rsa\rsa_saos.d
del %OPENSSL%\crypto\rsa\rsa_saos.o
del %OPENSSL%\crypto\rsa\rsa_sign.d
del %OPENSSL%\crypto\rsa\rsa_sign.o
del %OPENSSL%\crypto\rsa\rsa_ssl.d
del %OPENSSL%\crypto\rsa\rsa_ssl.o
del %OPENSSL%\crypto\rsa\rsa_x931.d
del %OPENSSL%\crypto\rsa\rsa_x931.o
del %OPENSSL%\crypto\rsa\rsa_x931g.d
del %OPENSSL%\crypto\rsa\rsa_x931g.o
del %OPENSSL%\crypto\seed\seed.d
del %OPENSSL%\crypto\seed\seed.o
del %OPENSSL%\crypto\seed\seed_cbc.d
del %OPENSSL%\crypto\seed\seed_cbc.o
del %OPENSSL%\crypto\seed\seed_cfb.d
del %OPENSSL%\crypto\seed\seed_cfb.o
del %OPENSSL%\crypto\seed\seed_ecb.d
del %OPENSSL%\crypto\seed\seed_ecb.o
del %OPENSSL%\crypto\seed\seed_ofb.d
del %OPENSSL%\crypto\seed\seed_ofb.o
del %OPENSSL%\crypto\sha\keccak1600.d
del %OPENSSL%\crypto\sha\keccak1600.o
del %OPENSSL%\crypto\sha\sha1-586.o
del %OPENSSL%\crypto\sha\sha1-586.s
del %OPENSSL%\crypto\sha\sha1_one.d
del %OPENSSL%\crypto\sha\sha1_one.o
del %OPENSSL%\crypto\sha\sha1dgst.d
del %OPENSSL%\crypto\sha\sha1dgst.o
del %OPENSSL%\crypto\sha\sha256-586.o
del %OPENSSL%\crypto\sha\sha256-586.s
del %OPENSSL%\crypto\sha\sha256.d
del %OPENSSL%\crypto\sha\sha256.o
del %OPENSSL%\crypto\sha\sha512-586.o
del %OPENSSL%\crypto\sha\sha512-586.s
del %OPENSSL%\crypto\sha\sha512.d
del %OPENSSL%\crypto\sha\sha512.o
del %OPENSSL%\crypto\siphash\siphash.d
del %OPENSSL%\crypto\siphash\siphash.o
del %OPENSSL%\crypto\siphash\siphash_ameth.d
del %OPENSSL%\crypto\siphash\siphash_ameth.o
del %OPENSSL%\crypto\siphash\siphash_pmeth.d
del %OPENSSL%\crypto\siphash\siphash_pmeth.o
del %OPENSSL%\crypto\sm2\sm2_crypt.d
del %OPENSSL%\crypto\sm2\sm2_crypt.o
del %OPENSSL%\crypto\sm2\sm2_err.d
del %OPENSSL%\crypto\sm2\sm2_err.o
del %OPENSSL%\crypto\sm2\sm2_pmeth.d
del %OPENSSL%\crypto\sm2\sm2_pmeth.o
del %OPENSSL%\crypto\sm2\sm2_sign.d
del %OPENSSL%\crypto\sm2\sm2_sign.o
del %OPENSSL%\crypto\sm3\m_sm3.d
del %OPENSSL%\crypto\sm3\m_sm3.o
del %OPENSSL%\crypto\sm3\sm3.d
del %OPENSSL%\crypto\sm3\sm3.o
del %OPENSSL%\crypto\sm4\sm4.d
del %OPENSSL%\crypto\sm4\sm4.o
del %OPENSSL%\crypto\srp\srp_lib.d
del %OPENSSL%\crypto\srp\srp_lib.o
del %OPENSSL%\crypto\srp\srp_vfy.d
del %OPENSSL%\crypto\srp\srp_vfy.o
del %OPENSSL%\crypto\stack\stack.d
del %OPENSSL%\crypto\stack\stack.o
del %OPENSSL%\crypto\store\loader_file.d
del %OPENSSL%\crypto\store\loader_file.o
del %OPENSSL%\crypto\store\store_err.d
del %OPENSSL%\crypto\store\store_err.o
del %OPENSSL%\crypto\store\store_init.d
del %OPENSSL%\crypto\store\store_init.o
del %OPENSSL%\crypto\store\store_lib.d
del %OPENSSL%\crypto\store\store_lib.o
del %OPENSSL%\crypto\store\store_register.d
del %OPENSSL%\crypto\store\store_register.o
del %OPENSSL%\crypto\store\store_strings.d
del %OPENSSL%\crypto\store\store_strings.o
del %OPENSSL%\crypto\threads_none.d
del %OPENSSL%\crypto\threads_none.o
del %OPENSSL%\crypto\threads_pthread.d
del %OPENSSL%\crypto\threads_pthread.o
del %OPENSSL%\crypto\threads_win.d
del %OPENSSL%\crypto\threads_win.o
del %OPENSSL%\crypto\ts\ts_asn1.d
del %OPENSSL%\crypto\ts\ts_asn1.o
del %OPENSSL%\crypto\ts\ts_conf.d
del %OPENSSL%\crypto\ts\ts_conf.o
del %OPENSSL%\crypto\ts\ts_err.d
del %OPENSSL%\crypto\ts\ts_err.o
del %OPENSSL%\crypto\ts\ts_lib.d
del %OPENSSL%\crypto\ts\ts_lib.o
del %OPENSSL%\crypto\ts\ts_req_print.d
del %OPENSSL%\crypto\ts\ts_req_print.o
del %OPENSSL%\crypto\ts\ts_req_utils.d
del %OPENSSL%\crypto\ts\ts_req_utils.o
del %OPENSSL%\crypto\ts\ts_rsp_print.d
del %OPENSSL%\crypto\ts\ts_rsp_print.o
del %OPENSSL%\crypto\ts\ts_rsp_sign.d
del %OPENSSL%\crypto\ts\ts_rsp_sign.o
del %OPENSSL%\crypto\ts\ts_rsp_utils.d
del %OPENSSL%\crypto\ts\ts_rsp_utils.o
del %OPENSSL%\crypto\ts\ts_rsp_verify.d
del %OPENSSL%\crypto\ts\ts_rsp_verify.o
del %OPENSSL%\crypto\ts\ts_verify_ctx.d
del %OPENSSL%\crypto\ts\ts_verify_ctx.o
del %OPENSSL%\crypto\txt_db\txt_db.d
del %OPENSSL%\crypto\txt_db\txt_db.o
del %OPENSSL%\crypto\ui\ui_err.d
del %OPENSSL%\crypto\ui\ui_err.o
del %OPENSSL%\crypto\ui\ui_lib.d
del %OPENSSL%\crypto\ui\ui_lib.o
del %OPENSSL%\crypto\ui\ui_null.d
del %OPENSSL%\crypto\ui\ui_null.o
del %OPENSSL%\crypto\ui\ui_openssl.d
del %OPENSSL%\crypto\ui\ui_openssl.o
del %OPENSSL%\crypto\ui\ui_util.d
del %OPENSSL%\crypto\ui\ui_util.o
del %OPENSSL%\crypto\uid.d
del %OPENSSL%\crypto\uid.o
del %OPENSSL%\crypto\uplink-x86.o
del %OPENSSL%\crypto\uplink-x86.s
del %OPENSSL%\crypto\whrlpool\wp-mmx.o
del %OPENSSL%\crypto\whrlpool\wp-mmx.s
del %OPENSSL%\crypto\whrlpool\wp_block.d
del %OPENSSL%\crypto\whrlpool\wp_block.o
del %OPENSSL%\crypto\whrlpool\wp_dgst.d
del %OPENSSL%\crypto\whrlpool\wp_dgst.o
del %OPENSSL%\crypto\x509\by_dir.d
del %OPENSSL%\crypto\x509\by_dir.o
del %OPENSSL%\crypto\x509\by_file.d
del %OPENSSL%\crypto\x509\by_file.o
del %OPENSSL%\crypto\x509\t_crl.d
del %OPENSSL%\crypto\x509\t_crl.o
del %OPENSSL%\crypto\x509\t_req.d
del %OPENSSL%\crypto\x509\t_req.o
del %OPENSSL%\crypto\x509\t_x509.d
del %OPENSSL%\crypto\x509\t_x509.o
del %OPENSSL%\crypto\x509\x509_att.d
del %OPENSSL%\crypto\x509\x509_att.o
del %OPENSSL%\crypto\x509\x509_cmp.d
del %OPENSSL%\crypto\x509\x509_cmp.o
del %OPENSSL%\crypto\x509\x509_d2.d
del %OPENSSL%\crypto\x509\x509_d2.o
del %OPENSSL%\crypto\x509\x509_def.d
del %OPENSSL%\crypto\x509\x509_def.o
del %OPENSSL%\crypto\x509\x509_err.d
del %OPENSSL%\crypto\x509\x509_err.o
del %OPENSSL%\crypto\x509\x509_ext.d
del %OPENSSL%\crypto\x509\x509_ext.o
del %OPENSSL%\crypto\x509\x509_lu.d
del %OPENSSL%\crypto\x509\x509_lu.o
del %OPENSSL%\crypto\x509\x509_meth.d
del %OPENSSL%\crypto\x509\x509_meth.o
del %OPENSSL%\crypto\x509\x509_obj.d
del %OPENSSL%\crypto\x509\x509_obj.o
del %OPENSSL%\crypto\x509\x509_r2x.d
del %OPENSSL%\crypto\x509\x509_r2x.o
del %OPENSSL%\crypto\x509\x509_req.d
del %OPENSSL%\crypto\x509\x509_req.o
del %OPENSSL%\crypto\x509\x509_set.d
del %OPENSSL%\crypto\x509\x509_set.o
del %OPENSSL%\crypto\x509\x509_trs.d
del %OPENSSL%\crypto\x509\x509_trs.o
del %OPENSSL%\crypto\x509\x509_txt.d
del %OPENSSL%\crypto\x509\x509_txt.o
del %OPENSSL%\crypto\x509\x509_v3.d
del %OPENSSL%\crypto\x509\x509_v3.o
del %OPENSSL%\crypto\x509\x509_vfy.d
del %OPENSSL%\crypto\x509\x509_vfy.o
del %OPENSSL%\crypto\x509\x509_vpm.d
del %OPENSSL%\crypto\x509\x509_vpm.o
del %OPENSSL%\crypto\x509\x509cset.d
del %OPENSSL%\crypto\x509\x509cset.o
del %OPENSSL%\crypto\x509\x509name.d
del %OPENSSL%\crypto\x509\x509name.o
del %OPENSSL%\crypto\x509\x509rset.d
del %OPENSSL%\crypto\x509\x509rset.o
del %OPENSSL%\crypto\x509\x509spki.d
del %OPENSSL%\crypto\x509\x509spki.o
del %OPENSSL%\crypto\x509\x509type.d
del %OPENSSL%\crypto\x509\x509type.o
del %OPENSSL%\crypto\x509\x_all.d
del %OPENSSL%\crypto\x509\x_all.o
del %OPENSSL%\crypto\x509\x_attrib.d
del %OPENSSL%\crypto\x509\x_attrib.o
del %OPENSSL%\crypto\x509\x_crl.d
del %OPENSSL%\crypto\x509\x_crl.o
del %OPENSSL%\crypto\x509\x_exten.d
del %OPENSSL%\crypto\x509\x_exten.o
del %OPENSSL%\crypto\x509\x_name.d
del %OPENSSL%\crypto\x509\x_name.o
del %OPENSSL%\crypto\x509\x_pubkey.d
del %OPENSSL%\crypto\x509\x_pubkey.o
del %OPENSSL%\crypto\x509\x_req.d
del %OPENSSL%\crypto\x509\x_req.o
del %OPENSSL%\crypto\x509\x_x509.d
del %OPENSSL%\crypto\x509\x_x509.o
del %OPENSSL%\crypto\x509\x_x509a.d
del %OPENSSL%\crypto\x509\x_x509a.o
del %OPENSSL%\crypto\x509v3\pcy_cache.d
del %OPENSSL%\crypto\x509v3\pcy_cache.o
del %OPENSSL%\crypto\x509v3\pcy_data.d
del %OPENSSL%\crypto\x509v3\pcy_data.o
del %OPENSSL%\crypto\x509v3\pcy_lib.d
del %OPENSSL%\crypto\x509v3\pcy_lib.o
del %OPENSSL%\crypto\x509v3\pcy_map.d
del %OPENSSL%\crypto\x509v3\pcy_map.o
del %OPENSSL%\crypto\x509v3\pcy_node.d
del %OPENSSL%\crypto\x509v3\pcy_node.o
del %OPENSSL%\crypto\x509v3\pcy_tree.d
del %OPENSSL%\crypto\x509v3\pcy_tree.o
del %OPENSSL%\crypto\x509v3\v3_addr.d
del %OPENSSL%\crypto\x509v3\v3_addr.o
del %OPENSSL%\crypto\x509v3\v3_admis.d
del %OPENSSL%\crypto\x509v3\v3_admis.o
del %OPENSSL%\crypto\x509v3\v3_akey.d
del %OPENSSL%\crypto\x509v3\v3_akey.o
del %OPENSSL%\crypto\x509v3\v3_akeya.d
del %OPENSSL%\crypto\x509v3\v3_akeya.o
del %OPENSSL%\crypto\x509v3\v3_alt.d
del %OPENSSL%\crypto\x509v3\v3_alt.o
del %OPENSSL%\crypto\x509v3\v3_asid.d
del %OPENSSL%\crypto\x509v3\v3_asid.o
del %OPENSSL%\crypto\x509v3\v3_bcons.d
del %OPENSSL%\crypto\x509v3\v3_bcons.o
del %OPENSSL%\crypto\x509v3\v3_bitst.d
del %OPENSSL%\crypto\x509v3\v3_bitst.o
del %OPENSSL%\crypto\x509v3\v3_conf.d
del %OPENSSL%\crypto\x509v3\v3_conf.o
del %OPENSSL%\crypto\x509v3\v3_cpols.d
del %OPENSSL%\crypto\x509v3\v3_cpols.o
del %OPENSSL%\crypto\x509v3\v3_crld.d
del %OPENSSL%\crypto\x509v3\v3_crld.o
del %OPENSSL%\crypto\x509v3\v3_enum.d
del %OPENSSL%\crypto\x509v3\v3_enum.o
del %OPENSSL%\crypto\x509v3\v3_extku.d
del %OPENSSL%\crypto\x509v3\v3_extku.o
del %OPENSSL%\crypto\x509v3\v3_genn.d
del %OPENSSL%\crypto\x509v3\v3_genn.o
del %OPENSSL%\crypto\x509v3\v3_ia5.d
del %OPENSSL%\crypto\x509v3\v3_ia5.o
del %OPENSSL%\crypto\x509v3\v3_info.d
del %OPENSSL%\crypto\x509v3\v3_info.o
del %OPENSSL%\crypto\x509v3\v3_int.d
del %OPENSSL%\crypto\x509v3\v3_int.o
del %OPENSSL%\crypto\x509v3\v3_lib.d
del %OPENSSL%\crypto\x509v3\v3_lib.o
del %OPENSSL%\crypto\x509v3\v3_ncons.d
del %OPENSSL%\crypto\x509v3\v3_ncons.o
del %OPENSSL%\crypto\x509v3\v3_pci.d
del %OPENSSL%\crypto\x509v3\v3_pci.o
del %OPENSSL%\crypto\x509v3\v3_pcia.d
del %OPENSSL%\crypto\x509v3\v3_pcia.o
del %OPENSSL%\crypto\x509v3\v3_pcons.d
del %OPENSSL%\crypto\x509v3\v3_pcons.o
del %OPENSSL%\crypto\x509v3\v3_pku.d
del %OPENSSL%\crypto\x509v3\v3_pku.o
del %OPENSSL%\crypto\x509v3\v3_pmaps.d
del %OPENSSL%\crypto\x509v3\v3_pmaps.o
del %OPENSSL%\crypto\x509v3\v3_prn.d
del %OPENSSL%\crypto\x509v3\v3_prn.o
del %OPENSSL%\crypto\x509v3\v3_purp.d
del %OPENSSL%\crypto\x509v3\v3_purp.o
del %OPENSSL%\crypto\x509v3\v3_skey.d
del %OPENSSL%\crypto\x509v3\v3_skey.o
del %OPENSSL%\crypto\x509v3\v3_sxnet.d
del %OPENSSL%\crypto\x509v3\v3_sxnet.o
del %OPENSSL%\crypto\x509v3\v3_tlsf.d
del %OPENSSL%\crypto\x509v3\v3_tlsf.o
del %OPENSSL%\crypto\x509v3\v3_utl.d
del %OPENSSL%\crypto\x509v3\v3_utl.o
del %OPENSSL%\crypto\x509v3\v3err.d
del %OPENSSL%\crypto\x509v3\v3err.o
del %OPENSSL%\crypto\x86cpuid.o
del %OPENSSL%\crypto\x86cpuid.s
del %OPENSSL%\engines\capi.dll
del %OPENSSL%\engines\dasync.dll
del %OPENSSL%\engines\e_capi.d
del %OPENSSL%\engines\e_capi.o
del %OPENSSL%\engines\e_dasync.d
del %OPENSSL%\engines\e_dasync.o
del %OPENSSL%\engines\e_ossltest.d
del %OPENSSL%\engines\e_ossltest.o
del %OPENSSL%\engines\e_padlock-x86.o
del %OPENSSL%\engines\e_padlock-x86.s
del %OPENSSL%\engines\e_padlock.d
del %OPENSSL%\engines\e_padlock.o
del %OPENSSL%\engines\ossltest.dll
del %OPENSSL%\engines\padlock.dll
del %OPENSSL%\fuzz\asn1-test.exe
del %OPENSSL%\fuzz\asn1.d
del %OPENSSL%\fuzz\asn1.o
del %OPENSSL%\fuzz\asn1parse-test.exe
del %OPENSSL%\fuzz\asn1parse.d
del %OPENSSL%\fuzz\asn1parse.o
del %OPENSSL%\fuzz\bignum-test.exe
del %OPENSSL%\fuzz\bignum.d
del %OPENSSL%\fuzz\bignum.o
del %OPENSSL%\fuzz\bndiv-test.exe
del %OPENSSL%\fuzz\bndiv.d
del %OPENSSL%\fuzz\bndiv.o
del %OPENSSL%\fuzz\client-test.exe
del %OPENSSL%\fuzz\client.d
del %OPENSSL%\fuzz\client.o
del %OPENSSL%\fuzz\cms-test.exe
del %OPENSSL%\fuzz\cms.d
del %OPENSSL%\fuzz\cms.o
del %OPENSSL%\fuzz\conf-test.exe
del %OPENSSL%\fuzz\conf.d
del %OPENSSL%\fuzz\conf.o
del %OPENSSL%\fuzz\crl-test.exe
del %OPENSSL%\fuzz\crl.d
del %OPENSSL%\fuzz\crl.o
del %OPENSSL%\fuzz\ct-test.exe
del %OPENSSL%\fuzz\ct.d
del %OPENSSL%\fuzz\ct.o
del %OPENSSL%\fuzz\libcrypto-1_1.dll
del %OPENSSL%\fuzz\libssl-1_1.dll
del %OPENSSL%\fuzz\server-test.exe
del %OPENSSL%\fuzz\server.d
del %OPENSSL%\fuzz\server.o
del %OPENSSL%\fuzz\test-corpus.d
del %OPENSSL%\fuzz\test-corpus.o
del %OPENSSL%\fuzz\x509-test.exe
del %OPENSSL%\fuzz\x509.d
del %OPENSSL%\fuzz\x509.o
del %OPENSSL%\include\crypto\bn_conf.h
del %OPENSSL%\include\crypto\dso_conf.h
del %OPENSSL%\include\openssl\opensslconf.h
del %OPENSSL%\libcrypto-1_1.dll
del %OPENSSL%\libcrypto.a
del %OPENSSL%\libcrypto.def
del %OPENSSL%\libcrypto.dll.a
del %OPENSSL%\libcrypto.pc
del %OPENSSL%\libcrypto.rc
del %OPENSSL%\libcrypto.res.o
del %OPENSSL%\libssl-1_1.dll
del %OPENSSL%\libssl.a
del %OPENSSL%\libssl.def
del %OPENSSL%\libssl.dll.a
del %OPENSSL%\libssl.pc
del %OPENSSL%\libssl.rc
del %OPENSSL%\libssl.res.o
del %OPENSSL%\ms\applink.d
del %OPENSSL%\ms\applink.o
del %OPENSSL%\ms\uplink.d
del %OPENSSL%\ms\uplink.o
del %OPENSSL%\openssl.pc
del %OPENSSL%\ssl\bio_ssl.d
del %OPENSSL%\ssl\bio_ssl.o
del %OPENSSL%\ssl\d1_lib.d
del %OPENSSL%\ssl\d1_lib.o
del %OPENSSL%\ssl\d1_msg.d
del %OPENSSL%\ssl\d1_msg.o
del %OPENSSL%\ssl\d1_srtp.d
del %OPENSSL%\ssl\d1_srtp.o
del %OPENSSL%\ssl\methods.d
del %OPENSSL%\ssl\methods.o
del %OPENSSL%\ssl\packet.d
del %OPENSSL%\ssl\packet.o
del %OPENSSL%\ssl\pqueue.d
del %OPENSSL%\ssl\pqueue.o
del %OPENSSL%\ssl\record\dtls1_bitmap.d
del %OPENSSL%\ssl\record\dtls1_bitmap.o
del %OPENSSL%\ssl\record\rec_layer_d1.d
del %OPENSSL%\ssl\record\rec_layer_d1.o
del %OPENSSL%\ssl\record\rec_layer_s3.d
del %OPENSSL%\ssl\record\rec_layer_s3.o
del %OPENSSL%\ssl\record\ssl3_buffer.d
del %OPENSSL%\ssl\record\ssl3_buffer.o
del %OPENSSL%\ssl\record\ssl3_record.d
del %OPENSSL%\ssl\record\ssl3_record.o
del %OPENSSL%\ssl\record\ssl3_record_tls13.d
del %OPENSSL%\ssl\record\ssl3_record_tls13.o
del %OPENSSL%\ssl\s3_cbc.d
del %OPENSSL%\ssl\s3_cbc.o
del %OPENSSL%\ssl\s3_enc.d
del %OPENSSL%\ssl\s3_enc.o
del %OPENSSL%\ssl\s3_lib.d
del %OPENSSL%\ssl\s3_lib.o
del %OPENSSL%\ssl\s3_msg.d
del %OPENSSL%\ssl\s3_msg.o
del %OPENSSL%\ssl\ssl_asn1.d
del %OPENSSL%\ssl\ssl_asn1.o
del %OPENSSL%\ssl\ssl_cert.d
del %OPENSSL%\ssl\ssl_cert.o
del %OPENSSL%\ssl\ssl_ciph.d
del %OPENSSL%\ssl\ssl_ciph.o
del %OPENSSL%\ssl\ssl_conf.d
del %OPENSSL%\ssl\ssl_conf.o
del %OPENSSL%\ssl\ssl_err.d
del %OPENSSL%\ssl\ssl_err.o
del %OPENSSL%\ssl\ssl_init.d
del %OPENSSL%\ssl\ssl_init.o
del %OPENSSL%\ssl\ssl_lib.d
del %OPENSSL%\ssl\ssl_lib.o
del %OPENSSL%\ssl\ssl_mcnf.d
del %OPENSSL%\ssl\ssl_mcnf.o
del %OPENSSL%\ssl\ssl_rsa.d
del %OPENSSL%\ssl\ssl_rsa.o
del %OPENSSL%\ssl\ssl_sess.d
del %OPENSSL%\ssl\ssl_sess.o
del %OPENSSL%\ssl\ssl_stat.d
del %OPENSSL%\ssl\ssl_stat.o
del %OPENSSL%\ssl\ssl_txt.d
del %OPENSSL%\ssl\ssl_txt.o
del %OPENSSL%\ssl\ssl_utst.d
del %OPENSSL%\ssl\ssl_utst.o
del %OPENSSL%\ssl\statem\extensions.d
del %OPENSSL%\ssl\statem\extensions.o
del %OPENSSL%\ssl\statem\extensions_clnt.d
del %OPENSSL%\ssl\statem\extensions_clnt.o
del %OPENSSL%\ssl\statem\extensions_cust.d
del %OPENSSL%\ssl\statem\extensions_cust.o
del %OPENSSL%\ssl\statem\extensions_srvr.d
del %OPENSSL%\ssl\statem\extensions_srvr.o
del %OPENSSL%\ssl\statem\statem.d
del %OPENSSL%\ssl\statem\statem.o
del %OPENSSL%\ssl\statem\statem_clnt.d
del %OPENSSL%\ssl\statem\statem_clnt.o
del %OPENSSL%\ssl\statem\statem_dtls.d
del %OPENSSL%\ssl\statem\statem_dtls.o
del %OPENSSL%\ssl\statem\statem_lib.d
del %OPENSSL%\ssl\statem\statem_lib.o
del %OPENSSL%\ssl\statem\statem_srvr.d
del %OPENSSL%\ssl\statem\statem_srvr.o
del %OPENSSL%\ssl\t1_enc.d
del %OPENSSL%\ssl\t1_enc.o
del %OPENSSL%\ssl\t1_lib.d
del %OPENSSL%\ssl\t1_lib.o
del %OPENSSL%\ssl\t1_trce.d
del %OPENSSL%\ssl\t1_trce.o
del %OPENSSL%\ssl\tls13_enc.d
del %OPENSSL%\ssl\tls13_enc.o
del %OPENSSL%\ssl\tls_srp.d
del %OPENSSL%\ssl\tls_srp.o
del %OPENSSL%\tools\c_rehash
del %OPENSSL%\util\shlib_wrap.sh
del %OPENSSL%\apps\libeay11.dll
del %OPENSSL%\apps\ssleay11.dll
del %OPENSSL%\fuzz\libeay11.dll
del %OPENSSL%\fuzz\ssleay11.dll
del %OPENSSL%\libeay11.dll
del %OPENSSL%\ssleay11.dll

if not "%1" == "" goto next

:libssh2

rmdir /S/Q %BUILD%\libssh2

if not "%1" == "" goto next

:iconv

del %ICONV%\Makefile
del %ICONV%\config.h
del %ICONV%\config.log
del %ICONV%\config.status
del %ICONV%\include\iconv.h
del %ICONV%\include\iconv.h.inst
del %ICONV%\lib\Makefile
del %ICONV%\lib\config.h
del %ICONV%\lib\stamp-h2
del %ICONV%\libcharset\Makefile
del %ICONV%\libcharset\config.h
del %ICONV%\libcharset\config.log
del %ICONV%\libcharset\config.status
del %ICONV%\libcharset\include\libcharset.h
del %ICONV%\libcharset\include\localcharset.h
del %ICONV%\libcharset\include\localcharset.h.inst
del %ICONV%\libcharset\lib\Makefile
del %ICONV%\libcharset\libtool
del %ICONV%\libtool
del %ICONV%\man\Makefile
del %ICONV%\po\Makefile
del %ICONV%\po\Makefile.in
del %ICONV%\po\POTFILES
del %ICONV%\src\Makefile
del %ICONV%\srclib\Makefile
del %ICONV%\stamp-h1
del %ICONV%\tests\Makefile
del %ICONV%\lib\libcharset.a
del %ICONV%\lib\libcharset.h
del %ICONV%\lib\libcharset.la
del %ICONV%\lib\libcharset.so
del %ICONV%\lib\libcharset.so.1
del %ICONV%\lib\libcharset.so.1.0.0
del %ICONV%\lib\localcharset.h
del %ICONV%\libcharset\lib\libcharset.la
del %ICONV%\libcharset\lib\localcharset.lo
del %ICONV%\libcharset\lib\localcharset.o
del %ICONV%\libcharset\lib\relocatable-stub.lo
del %ICONV%\libcharset\lib\relocatable-stub.o
del %ICONV%\lib\iconv.lo
del %ICONV%\lib\libiconv.la
del %ICONV%\lib\localcharset.lo
del %ICONV%\lib\relocatable.lo
del %ICONV%\src\iconv.o
del %ICONV%\src\iconv_no_i18n.exe
del %ICONV%\src\iconv_no_i18n.o
del %ICONV%\srclib\alloca.h
del %ICONV%\srclib\allocator.o
del %ICONV%\srclib\areadlink.o
del %ICONV%\srclib\basename-lgpl.o
del %ICONV%\srclib\binary-io.o
del %ICONV%\srclib\canonicalize-lgpl.o
del %ICONV%\srclib\careadlinkat.o
del %ICONV%\srclib\dirname-lgpl.o
del %ICONV%\srclib\errno.h
del %ICONV%\srclib\error.o
del %ICONV%\srclib\fcntl.h
del %ICONV%\srclib\getprogname.o
del %ICONV%\srclib\libicrt.a
del %ICONV%\srclib\limits.h
del %ICONV%\srclib\malloc.o
del %ICONV%\srclib\malloca.o
del %ICONV%\srclib\progname.o
del %ICONV%\srclib\raise.o
del %ICONV%\srclib\readlink.o
del %ICONV%\srclib\safe-read.o
del %ICONV%\srclib\signal.h
del %ICONV%\srclib\sigprocmask.o
del %ICONV%\srclib\stat-time.o
del %ICONV%\srclib\stdint.h
del %ICONV%\srclib\stdio-write.o
del %ICONV%\srclib\stdio.h
del %ICONV%\srclib\stdlib.h
del %ICONV%\srclib\strerror-override.o
del %ICONV%\srclib\strerror.o
del %ICONV%\srclib\string.h
del %ICONV%\srclib\stripslash.o
del %ICONV%\srclib\time.h
del %ICONV%\srclib\unistd.h
del %ICONV%\srclib\unistd.o
del %ICONV%\srclib\unitypes.h
del %ICONV%\srclib\uniwidth.h
del %ICONV%\srclib\uniwidth\.dirstamp
del %ICONV%\srclib\uniwidth\width.o
del %ICONV%\srclib\xmalloc.o
del %ICONV%\srclib\xreadlink.o
del %ICONV%\srclib\xstrdup.o
del %ICONV%\srclib\stat-w32.o
del %ICONV%\srclib\stat.o
del %ICONV%\src\iconv.res
del %ICONV%\lib\iconv-exports.lo
del %ICONV%\lib\libcharset.dll.a
del %ICONV%\lib\libiconv.res.lo
del %ICONV%\lib\charset.dll
del %ICONV%\lib\iconv-exports.o
del %ICONV%\lib\iconv.o
del %ICONV%\lib\libiconv.res.o
del %ICONV%\lib\localcharset.o
del %ICONV%\lib\relocatable.o
del %ICONV%\src\iconv.exe
del %ICONV%\lib\libiconv.def
del %ICONV%\libcharset\lib\libcharset.def
del %ICONV%\confdefs.h
del %ICONV%\conftest.c
del %ICONV%\conftest.err
del %ICONV%\lib\libiconv.dll.a
del %ICONV%\libcharset\lib\libcharset.dll.a
rmdir /S/Q %ICONV%\bin
rmdir /S/Q %ICONV%\libcharset\lib\.libs
rmdir /S/Q %ICONV%\srclib\sys
rmdir /S/Q %ICONV%\lib\.libs
rmdir /S/Q %ICONV%\src\.libs
rmdir /S/Q %ICONV%\conftest*

if not "%1" == "" goto next

:curl

rmdir /S/Q %BUILD%\curl

if not "%1" == "" goto next

:expat

rmdir /S/Q %BUILD%\expat

if not "%1" == "" goto next

:pcre2

rmdir /S/Q %BUILD%\pcre2

if not "%1" == "" goto next

:ncurses

del %NCURSES%\conf*.src
del %NCURSES%\conftest.c
del %NCURSES%\conftest.err
del %NCURSES%\conftest.er1
del %NCURSES%\conftest.exe
del %NCURSES%\conftest*
del %NCURSES%\Makefile
del %NCURSES%\c++\Makefile
del %NCURSES%\config.log
del %NCURSES%\config.status
del %NCURSES%\edit_man.sh
del %NCURSES%\form\Makefile
del %NCURSES%\headers.sh
del %NCURSES%\include\MKterm.h.awk
del %NCURSES%\include\Makefile
del %NCURSES%\include\curses.head
del %NCURSES%\include\ncurses_cfg.h
del %NCURSES%\include\ncurses_dll.h
del %NCURSES%\include\termcap.h
del %NCURSES%\include\unctrl.h
del %NCURSES%\man\Makefile
del %NCURSES%\man\ncurses6-config.1
del %NCURSES%\menu\Makefile
del %NCURSES%\misc\Makefile
del %NCURSES%\misc\ncurses-config
del %NCURSES%\misc\run_tic.sh
del %NCURSES%\mk_shared_lib.sh
del %NCURSES%\ncurses\Makefile
del %NCURSES%\panel\Makefile
del %NCURSES%\progs\Makefile
del %NCURSES%\test\Makefile
del %NCURSES%\include\config.h
del %NCURSES%\include\curses.h
del %NCURSES%\include\hashsize.h
del %NCURSES%\include\ncurses_def.h
del %NCURSES%\include\parametrized.h
del %NCURSES%\include\term.h
del %NCURSES%\man\terminfo.5
del %NCURSES%\ncurses\codes.c
del %NCURSES%\ncurses\expanded.c
del %NCURSES%\ncurses\fallback.c
del %NCURSES%\ncurses\lib_gen.c
del %NCURSES%\conf1091.src
del %NCURSES%\confdefs.h
del %NCURSES%\conftest.cc
del %NCURSES%\ncurses\comp_captab.c
del %NCURSES%\ncurses\comp_userdefs.c
del %NCURSES%\ncurses\init_keytry.h
del %NCURSES%\ncurses\keys.list
del %NCURSES%\ncurses\lib_keyname.c
del %NCURSES%\ncurses\link_test.c
del %NCURSES%\ncurses\make_hash.exe
del %NCURSES%\ncurses\make_keys.exe
del %NCURSES%\ncurses\names.c
del %NCURSES%\ncurses\report_offsets.exe
del %NCURSES%\ncurses\unctrl.c
del %NCURSES%\progs\termsort.h
del %NCURSES%\progs\transform.h
del %NCURSES%\man\ncursesw6-config.1
del %NCURSES%\c++\demo.exe
del %NCURSES%\c++\etip.h
del %NCURSES%\include\eti.h
del %NCURSES%\include\form.h
del %NCURSES%\include\menu.h
del %NCURSES%\include\mf_common.h
del %NCURSES%\include\panel.h
del %NCURSES%\misc\run_tic.sed
del %NCURSES%\misc\terminfo.tmp
del %NCURSES%\progs\clear.exe
del %NCURSES%\progs\infocmp.exe
del %NCURSES%\progs\tabs.exe
del %NCURSES%\progs\tic.exe
del %NCURSES%\progs\toe.exe
del %NCURSES%\progs\tput.exe
del %NCURSES%\progs\tset.exe
del %NCURSES%\test\back_ground.exe
del %NCURSES%\test\background.exe
del %NCURSES%\test\blue.exe
del %NCURSES%\test\bs.exe
del %NCURSES%\test\cardfile.exe
del %NCURSES%\test\chgat.exe
del %NCURSES%\test\clip_printw.exe
del %NCURSES%\test\color_content.exe
del %NCURSES%\test\color_set.exe
del %NCURSES%\test\demo_altkeys.exe
del %NCURSES%\test\demo_defkey.exe
del %NCURSES%\test\demo_forms.exe
del %NCURSES%\test\demo_keyok.exe
del %NCURSES%\test\demo_menus.exe
del %NCURSES%\test\demo_new_pair.exe
del %NCURSES%\test\demo_panels.exe
del %NCURSES%\test\demo_tabs.exe
del %NCURSES%\test\demo_termcap.exe
del %NCURSES%\test\demo_terminfo.exe
del %NCURSES%\test\ditto.exe
del %NCURSES%\test\dots.exe
del %NCURSES%\test\dots_curses.exe
del %NCURSES%\test\dots_mvcur.exe
del %NCURSES%\test\dots_termcap.exe
del %NCURSES%\test\dots_xcurses.exe
del %NCURSES%\test\dup_field.exe
del %NCURSES%\test\echochar.exe
del %NCURSES%\test\extended_color.exe
del %NCURSES%\test\filter.exe
del %NCURSES%\test\firework.exe
del %NCURSES%\test\firstlast.exe
del %NCURSES%\test\foldkeys.exe
del %NCURSES%\test\form_driver_w.exe
del %NCURSES%\test\gdc.exe
del %NCURSES%\test\hanoi.exe
del %NCURSES%\test\hashtest.exe
del %NCURSES%\test\inch_wide.exe
del %NCURSES%\test\inchs.exe
del %NCURSES%\test\ins_wide.exe
del %NCURSES%\test\insdelln.exe
del %NCURSES%\test\inserts.exe
del %NCURSES%\test\key_names.exe
del %NCURSES%\test\keynames.exe
del %NCURSES%\test\knight.exe
del %NCURSES%\test\list_keys.exe
del %NCURSES%\test\lrtest.exe
del %NCURSES%\test\move_field.exe
del %NCURSES%\test\movewindow.exe
del %NCURSES%\test\ncurses.exe
del %NCURSES%\test\newdemo.exe
del %NCURSES%\test\padview.exe
del %NCURSES%\test\pair_content.exe
del %NCURSES%\test\picsmap.exe
del %NCURSES%\test\railroad.exe
del %NCURSES%\test\rain.exe
del %NCURSES%\test\redraw.exe
del %NCURSES%\test\savescreen.exe
del %NCURSES%\test\sp_tinfo.exe
del %NCURSES%\test\tclock.exe
del %NCURSES%\test\test_add_wchstr.exe
del %NCURSES%\test\test_addchstr.exe
del %NCURSES%\test\test_addstr.exe
del %NCURSES%\test\test_addwstr.exe
del %NCURSES%\test\test_arrays.exe
del %NCURSES%\test\test_get_wstr.exe
del %NCURSES%\test\test_getstr.exe
del %NCURSES%\test\test_instr.exe
del %NCURSES%\test\test_inwstr.exe
del %NCURSES%\test\test_opaque.exe
del %NCURSES%\test\test_setupterm.exe
del %NCURSES%\test\test_sgr.exe
del %NCURSES%\test\test_termattrs.exe
del %NCURSES%\test\test_tparm.exe
del %NCURSES%\test\test_vid_puts.exe
del %NCURSES%\test\test_vidputs.exe
del %NCURSES%\test\testaddch.exe
del %NCURSES%\test\testcurs.exe
del %NCURSES%\test\testscanw.exe
del %NCURSES%\test\view.exe
del %NCURSES%\test\worm.exe
del %NCURSES%\test\xmas.exe
rmdir /S/Q %NCURSES%\misc\tabset\_tabset_
rmdir /S/Q %NCURSES%\misc\_terminfo_
rmdir /S/Q %NCURSES%\misc\_tabset_
rmdir /S/Q %NCURSES%\lib
rmdir /S/Q %NCURSES%\obj_g
rmdir /S/Q %NCURSES%\objects

if not "%1" == "" goto next

:less

rmdir /S/Q %LESS%\conf*.dir
del %LESS%\config.log
del %LESS%\confdefs.h
del %LESS%\conftest.c
del %LESS%\conftest.err
del %LESS%\conftest.exe
del %LESS%\Makefile
del %LESS%\config.status
del %LESS%\defines.h
del %LESS%\main.o
del %LESS%\stamp-h
del %LESS%\brac.o
del %LESS%\ch.o
del %LESS%\charset.o
del %LESS%\cmdbuf.o
del %LESS%\command.o
del %LESS%\cvt.o
del %LESS%\decode.o
del %LESS%\edit.o
del %LESS%\filename.o
del %LESS%\forwback.o
del %LESS%\help.o
del %LESS%\ifile.o
del %LESS%\input.o
del %LESS%\jump.o
del %LESS%\less.exe
del %LESS%\lessecho.exe
del %LESS%\lessecho.o
del %LESS%\lesskey.exe
del %LESS%\lesskey.o
del %LESS%\lesskey_parse.o
del %LESS%\line.o
del %LESS%\linenum.o
del %LESS%\lsystem.o
del %LESS%\mark.o
del %LESS%\optfunc.o
del %LESS%\option.o
del %LESS%\opttbl.o
del %LESS%\os.o
del %LESS%\output.o
del %LESS%\pattern.o
del %LESS%\position.o
del %LESS%\prompt.o
del %LESS%\screen.o
del %LESS%\search.o
del %LESS%\signal.o
del %LESS%\tags.o
del %LESS%\ttyin.o
del %LESS%\version.o
del %LESS%\xbuf.o

if not "%1" == "" goto next

:openssh

rmdir /S/Q %BUILD%\openssh

if not "%1" == "" goto next

:putty

del %PUTTY%\windows\agentf.o
del %PUTTY%\windows\aqsync.o
del %PUTTY%\windows\be_all_s.o
del %PUTTY%\windows\be_misc.o
del %PUTTY%\windows\be_ssh.o
del %PUTTY%\windows\callback.o
del %PUTTY%\windows\clicons.o
del %PUTTY%\windows\cmdline.o
del %PUTTY%\windows\conf.o
del %PUTTY%\windows\config.o
del %PUTTY%\windows\console.o
del %PUTTY%\windows\cproxy.o
del %PUTTY%\windows\dialog.o
del %PUTTY%\windows\ecc.o
del %PUTTY%\windows\errsock.o
del %PUTTY%\windows\ldisc.o
del %PUTTY%\windows\logging.o
del %PUTTY%\windows\mainchan.o
del %PUTTY%\windows\marshal.o
del %PUTTY%\windows\memory.o
del %PUTTY%\windows\minibidi.o
del %PUTTY%\windows\misc.o
del %PUTTY%\windows\miscucs.o
del %PUTTY%\windows\mpint.o
del %PUTTY%\windows\nocproxy.o
del %PUTTY%\windows\norand.o
del %PUTTY%\windows\noterm.o
del %PUTTY%\windows\nullplug.o
del %PUTTY%\windows\pageant.map
del %PUTTY%\windows\pageant.o
del %PUTTY%\windows\pageant.res.o
del %PUTTY%\windows\pgssapi.o
del %PUTTY%\windows\pinger.o
del %PUTTY%\windows\plink.map
del %PUTTY%\windows\plink.res.o
del %PUTTY%\windows\portfwd.o
del %PUTTY%\windows\proxy.o
del %PUTTY%\windows\pscp.map
del %PUTTY%\windows\pscp.o
del %PUTTY%\windows\pscp.res.o
del %PUTTY%\windows\psftp.map
del %PUTTY%\windows\psftp.o
del %PUTTY%\windows\psftp.res.o
del %PUTTY%\windows\psftpcommon.o
del %PUTTY%\windows\psocks.o
del %PUTTY%\windows\putty.res.o
del %PUTTY%\windows\raw.o
del %PUTTY%\windows\rlogin.o
del %PUTTY%\windows\sessprep.o
del %PUTTY%\windows\settings.o
del %PUTTY%\windows\sftp.o
del %PUTTY%\windows\sftpcommon.o
del %PUTTY%\windows\sizetip.o
del %PUTTY%\windows\ssh.o
del %PUTTY%\windows\ssh1bpp.o
del %PUTTY%\windows\ssh1censor.o
del %PUTTY%\windows\ssh1connection-client.o
del %PUTTY%\windows\ssh1connection.o
del %PUTTY%\windows\ssh1login.o
del %PUTTY%\windows\ssh2bpp-bare.o
del %PUTTY%\windows\ssh2bpp.o
del %PUTTY%\windows\ssh2censor.o
del %PUTTY%\windows\ssh2connection-client.o
del %PUTTY%\windows\ssh2connection.o
del %PUTTY%\windows\ssh2kex-client.o
del %PUTTY%\windows\ssh2transhk.o
del %PUTTY%\windows\ssh2transport.o
del %PUTTY%\windows\ssh2userauth.o
del %PUTTY%\windows\sshaes.o
del %PUTTY%\windows\ssharcf.o
del %PUTTY%\windows\sshargon2.o
del %PUTTY%\windows\sshauxcrypt.o
del %PUTTY%\windows\sshblake2.o
del %PUTTY%\windows\sshblowf.o
del %PUTTY%\windows\sshccp.o
del %PUTTY%\windows\sshcommon.o
del %PUTTY%\windows\sshcrc.o
del %PUTTY%\windows\sshcrcda.o
del %PUTTY%\windows\sshdes.o
del %PUTTY%\windows\sshdh.o
del %PUTTY%\windows\sshdss.o
del %PUTTY%\windows\sshecc.o
del %PUTTY%\windows\sshgssc.o
del %PUTTY%\windows\sshhmac.o
del %PUTTY%\windows\sshmac.o
del %PUTTY%\windows\sshmd5.o
del %PUTTY%\windows\sshprng.o
del %PUTTY%\windows\sshpubk.o
del %PUTTY%\windows\sshrand.o
del %PUTTY%\windows\sshrsa.o
del %PUTTY%\windows\sshsh256.o
del %PUTTY%\windows\sshsh512.o
del %PUTTY%\windows\sshsha.o
del %PUTTY%\windows\sshsha3.o
del %PUTTY%\windows\sshshare.o
del %PUTTY%\windows\sshutils.o
del %PUTTY%\windows\sshverstring.o
del %PUTTY%\windows\sshzlib.o
del %PUTTY%\windows\stripctrl.o
del %PUTTY%\windows\supdup.o
del %PUTTY%\windows\telnet.o
del %PUTTY%\windows\terminal.o
del %PUTTY%\windows\time.o
del %PUTTY%\windows\timing.o
del %PUTTY%\windows\tree234.o
del %PUTTY%\windows\utils.o
del %PUTTY%\windows\version.o
del %PUTTY%\windows\wcwidth.o
del %PUTTY%\windows\wildcard.o
del %PUTTY%\windows\wincapi.o
del %PUTTY%\windows\wincfg.o
del %PUTTY%\windows\wincliloop.o
del %PUTTY%\windows\wincons.o
del %PUTTY%\windows\winctrls.o
del %PUTTY%\windows\windefs.o
del %PUTTY%\windows\windlg.o
del %PUTTY%\windows\wingss.o
del %PUTTY%\windows\winhandl.o
del %PUTTY%\windows\winhelp.o
del %PUTTY%\windows\winhsock.o
del %PUTTY%\windows\winjump.o
del %PUTTY%\windows\winmisc.o
del %PUTTY%\windows\winmiscs.o
del %PUTTY%\windows\winnet.o
del %PUTTY%\windows\winnohlp.o
del %PUTTY%\windows\winnoise.o
del %PUTTY%\windows\winnojmp.o
del %PUTTY%\windows\winnpc.o
del %PUTTY%\windows\winnps.o
del %PUTTY%\windows\winpgnt.o
del %PUTTY%\windows\winpgntc.o
del %PUTTY%\windows\winplink.o
del %PUTTY%\windows\winproxy.o
del %PUTTY%\windows\winsecur.o
del %PUTTY%\windows\winselcli.o
del %PUTTY%\windows\winselgui.o
del %PUTTY%\windows\winser.o
del %PUTTY%\windows\winsftp.o
del %PUTTY%\windows\winshare.o
del %PUTTY%\windows\winsocks.o
del %PUTTY%\windows\winstore.o
del %PUTTY%\windows\wintime.o
del %PUTTY%\windows\winucs.o
del %PUTTY%\windows\winutils.o
del %PUTTY%\windows\winx11.o
del %PUTTY%\windows\x11fwd.o
del %PUTTY%\windows\be_nos_s.o
del %PUTTY%\windows\import.o
del %PUTTY%\windows\millerrabin.o
del %PUTTY%\windows\mpunsafe.o
del %PUTTY%\windows\nogss.o
del %PUTTY%\windows\notiming.o
del %PUTTY%\windows\pageant.exe
del %PUTTY%\windows\plink.exe
del %PUTTY%\windows\pockle.o
del %PUTTY%\windows\primecandidate.o
del %PUTTY%\windows\pscp.exe
del %PUTTY%\windows\psftp.exe
del %PUTTY%\windows\psocks.exe
del %PUTTY%\windows\psocks.map
del %PUTTY%\windows\putty.exe
del %PUTTY%\windows\putty.map
del %PUTTY%\windows\puttygen.exe
del %PUTTY%\windows\puttygen.map
del %PUTTY%\windows\puttygen.res.o
del %PUTTY%\windows\puttytel.exe
del %PUTTY%\windows\puttytel.map
del %PUTTY%\windows\puttytel.res.o
del %PUTTY%\windows\smallprimes.o
del %PUTTY%\windows\sshbcrypt.o
del %PUTTY%\windows\sshdssg.o
del %PUTTY%\windows\sshecdsag.o
del %PUTTY%\windows\sshprime.o
del %PUTTY%\windows\sshrsag.o
del %PUTTY%\windows\testcrypt.exe
del %PUTTY%\windows\testcrypt.map
del %PUTTY%\windows\testcrypt.o
del %PUTTY%\windows\window.o
del %PUTTY%\windows\winpgen.o
del %PUTTY%\windows\winprint.o

if not "%1" == "" goto next

:git

del %GIT%\GIT-VERSION-FILE
rmdir /S/Q %BUILD%\git

if not "%1" == "" goto next

:done
echo DONE!
exit

:next
shift
if not "%1" == "" goto :%1
goto done

:error
echo ERROR!
