/* XPM */
static const char *const cfg_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 9 1 ",
"  c None",
". c black",
"X c #808000",
"o c yellow",
"O c navy",
"+ c blue",
"@ c #808080",
"# c #C0C0C0",
"$ c white",
/* pixels */
"   ..  .......  ",
"  .oo..$$$$$#@. ",
" . .Xo.$++OO#@. ",
".X. .Xo@+OoO#@. ",
".Xo..oo.OoO+#@. ",
" .XooooXo@@##@. ",
"  .XXXooXoo.@@@.",
" .$.XXXoo.@@@@@.",
" .$+OOXXoo.@@@. ",
" .$+OoO.Xoo...  ",
" .$OoO+#.Xoo.   ",
" .#@@###@.Xoo.  ",
" .@@@@@@@@.Xoo. ",
".$$$$$@@@@..Xoo.",
".#@@@@@@@.  .Xo.",
" ........    .. "
};

/* XPM */
static const char *const cfg_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 9 1 ",
"  c None",
". c black",
"X c #808000",
"o c yellow",
"O c navy",
"+ c blue",
"@ c #808080",
"# c #C0C0C0",
"$ c white",
/* pixels */
"                ............    ",
"      ..       .###########@.   ",
"     .oo..    .$$$$$$$$$$#@@.   ",
"     .XXoo.   .$OOOOOOOOO#@@.   ",
"      .XXoo.  .$O++++++++#@@.   ",
"  ..   .Xoo.  .$O++++..++#@@.   ",
" .Xo.  .Xooo. .$O+++.o.++#@@.   ",
" .Xoo..Xoooo. .$O+..o.+++#@@.   ",
"  .Xooooooo.  .$O.oo.++++#@@.   ",
"  .XXooooooo. .$.oo.+++++#@@.   ",
"   .XXXXXXooo...oo.$$$$$$#@@... ",
"    ..XX.XXooo.oo.@@@@@@@@@.#$@.",
"      .. .XXooo............#$@@.",
"          .XXooo.oooo.$$$$$$#@@.",
"     .....o.XXooo.o..#######@@@.",
"    .#####...XXooo.##@....@#@@. ",
"   .$$$$$$$$$.XXooo.@@@@@@@@@.  ",
"   .$OOOOOOO.o.XXooo.........   ",
"   .$O+++++.oo..XXooo.          ",
"   .$O++++.oo.#@.XXooo.         ",
"   .$O+++.o..+#@@.XXooo.        ",
"   .$O++.o.+++#@@..XXooo.       ",
"   .$O++..++++#@@. .XXooo.      ",
"   .$O++++++++#@@.  .XXooo.     ",
"   .$$$$$$$$$$#@@... .XXooo.    ",
"  ..#@@@@@@@@@@@.#$@. .XXooo.   ",
" .#.............#$@@.  .XXooo.  ",
".$$$$$$$$$$$$$$$$#@@.   .XXo.   ",
".$###############@@@.    .X.    ",
".$########@....@#@@.      .     ",
".#@@@@@@@@@@@@@@@@.             ",
" .................              "
};

/* XPM */
static const char *const cfg_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 9 1 ",
"  c None",
". c black",
"X c #808000",
"o c yellow",
"O c navy",
"+ c blue",
"@ c #808080",
"# c #C0C0C0",
"$ c white",
/* pixels */
"                         ..................     ",
"                        .#################@.    ",
"         ..            .#################@@.    ",
"        .oo...        .$$$$$$$$$$$$$$$$#@@@.    ",
"        .Xoooo.       .$@@@@@@@@@@@@@@#@@@@.    ",
"         .XXooo.      .$@OOOOOOOOOOOOO$@@@@.    ",
"          .XXooo.     .$@O++++++++++++$@@@@.    ",
"           .Xooo.     .$@O++++++++++++$@@@@.    ",
"   ..      .Xooo.     .$@O+++++++..+++$@@@@.    ",
"  .Xo.     .Xoooo.    .$@O++++++.o.+++$@@@@.    ",
"  .XXo.    .Xoooo.    .$@O+++++.o.++++$@@@@.    ",
"   .Xoo....ooooo.     .$@O+++..o.+++++$@@@@.    ",
"   .XXooooooooooo.    .$@O++.oo.++++++$@@@@.    ",
"   .XXoooooooooooo.   .$@O+.oo.+++++++$@@@@.    ",
"    .XXXooooXoooooo.  .$#..oo.$$$$$$$$$@@@@.... ",
"     .XXXXXXXooooooo...$.ooo.##########@@@.#$$@.",
"      ...XX.XXooooooo...oo..@@@@@@@@@@@@@.#$$@@.",
"         .. .XXooooooo.oo................#$$@@@.",
"             .XXooooooo........$$$$$$$$$$$$#@@@.",
"              .XXooooooo.oooooo.$$$$$$$$$$#@@@@.",
"               .XXooooooo.ooo..##@.......#@@@@. ",
"                .XXooooooo.o.@@@@@@@@@@@@@@@@.  ",
"               .o.XXooooooo.@@@@@@@@@@@@@@@@.   ",
"                ...XXooooooo................    ",
"       .............XXooooooo.                  ",
"      .############..XXooooooo.                 ",
"     .############.oo.XXooooooo.                ",
"    .$$$$$$$$$$$$.oo...XXooooooo.               ",
"    .$@@@@@@@@@@.oo.#@@.XXooooooo.              ",
"    .$@OOOOOOOO.oo.O$@@@.XXooooooo.             ",
"    .$@O++++++.o..++$@@@@.XXooooooo.            ",
"    .$@O+++++.o.++++$@@@@..XXooooooo.           ",
"    .$@O++++.o.+++++$@@@@. .XXooooooo.          ",
"    .$@O++++..++++++$@@@@.  .XXooooooo.         ",
"    .$@O++++++++++++$@@@@.   .XXooooooo.        ",
"    .$@O++++++++++++$@@@@.    .XXooooooo.       ",
"    .$@O++++++++++++$@@@@.     .XXooooooo.      ",
"    .$@O++++++++++++$@@@@.      .XXooooooo.     ",
"    .$#$$$$$$$$$$$$$$@@@@....    .XXooooooo.    ",
"   ..$###############@@@.#$$@.    .XXooooooo.   ",
"  .#.#@@@@@@@@@@@@@@@@@.#$$@@.     .XXooooo.    ",
" .##...................#$$@@@.      .XXooo.     ",
".$$$$$$$$$$$$$$$$$$$$$$$$#@@@.       .XXo.      ",
".$$$$$$$$$$$$$$$$$$$$$$$#@@@@.        .X.       ",
".$$############@.......#@@@@.          .        ",
".##@@@@@@@@@@@@@@@@@@@@@@@@.                    ",
".##@@@@@@@@@@@@@@@@@@@@@@@.                     ",
" .........................                      "
};

const char *const *const cfg_icon[] = {
    cfg_icon_0,
    cfg_icon_1,
    cfg_icon_2,
};
const int n_cfg_icon = 3;
