/* XPM */
static const char *const cfg_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 9 1 ",
"  c None",
". c black",
"X c #808000",
"o c yellow",
"O c navy",
"+ c blue",
"@ c #808080",
"# c #C0C0C0",
"$ c white",
/* pixels */
"   ..           ",
"  .oo.......    ",
" ..@Xo@$$$#@.   ",
".X.$OXoO++#@.   ",
".Xo@OooO++#@.   ",
" .XooooO++#@.   ",
"  .XXXooO+#@.   ",
"  .@OOXooO#@.   ",
"  .###@Xoo@@..  ",
" .@@@@@.Xoo.$@. ",
".$$$$$$$@Xoo@@. ",
".$#####@@.Xoo.. ",
".#@@@@@@@@.Xoo. ",
" ...........Xoo.",
"            .Xo.",
"             .. "
};

/* XPM */
static const char *const cfg_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 9 1 ",
"  c None",
". c black",
"X c #808000",
"o c yellow",
"O c navy",
"+ c blue",
"@ c #808080",
"# c #C0C0C0",
"$ c white",
/* pixels */
"                                ",
"      ..                        ",
"     .oo..                      ",
"     .XXoo.                     ",
"      .XXoo...............      ",
"  ..   .Xoo.#############@.     ",
" .Xo.  .Xooo.###########@@.     ",
" .Xoo..Xoooo.$$$$$$$$$#@@@.     ",
"  .Xooooooo.OOOOOOOOOO#@@@.     ",
"  .XXooooooo.+++++++++#@@@.     ",
"   .XXXXXXooo.++++++++#@@@.     ",
"    ..XX.XXooo.+++++++#@@@.     ",
"      ..O.XXooo.++++++#@@@.     ",
"      .$O+.XXooo.+++++#@@@.     ",
"      .$O++.XXooo.++++#@@@.     ",
"      .$O+++.XXooo.+++#@@@.     ",
"      .$O++++.XXooo.++#@@@.     ",
"      .$$$$$$$.XXooo.$#@@@...   ",
"     ..$#######.XXooo.@@@.#$@.  ",
"    .#.#@@@@@@@@.XXooo.@.#$@@.  ",
"   .##............XXooo.#$@@@.  ",
"  .$$$$$$$$$$$$$$$.XXooo.#@@@.  ",
"  .$###############.XXooo.@@@.  ",
"  .$################.XXooo.@.   ",
"  .$############@.....XXooo.    ",
"  .#@@@@@@@@@@@@@@@@@@.XXooo.   ",
"   .....................XXooo.  ",
"                        .XXo.   ",
"                         .X.    ",
"                          .     ",
"                                ",
"                                "
};

/* XPM */
static const char *const cfg_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 9 1 ",
"  c None",
". c black",
"X c #808000",
"o c yellow",
"O c navy",
"+ c blue",
"@ c #808080",
"# c #C0C0C0",
"$ c white",
/* pixels */
"                                                ",
"                                                ",
"         ..                                     ",
"        .oo...                                  ",
"        .Xoooo.                                 ",
"         .XXooo.                                ",
"          .XXooo.                               ",
"           .Xooo......................          ",
"   ..      .Xooo.####################@.         ",
"  .Xo.     .Xoooo.##################@@.         ",
"  .XXo.   ..Xoooo.#################@@@.         ",
"   .Xoo....ooooo.$$$$$$$$$$$$$$$$#@@@@.         ",
"   .XXooooooooooo.@@@@@@@@@@@@@@#@@@@@.         ",
"   .XXoooooooooooo.OOOOOOOOOOOOO$@@@@@.         ",
"    .XXXooooXoooooo.++++++++++++$@@@@@.         ",
"     .XXXXXXXooooooo.+++++++++++$@@@@@.         ",
"      ...XX.XXooooooo.++++++++++$@@@@@.         ",
"         ..@.XXooooooo.+++++++++$@@@@@.         ",
"         .$@O.XXooooooo.++++++++$@@@@@.         ",
"         .$@O+.XXooooooo.+++++++$@@@@@.         ",
"         .$@O++.XXooooooo.++++++$@@@@@.         ",
"         .$@O+++.XXooooooo.+++++$@@@@@.         ",
"         .$@O++++.XXooooooo.++++$@@@@@.         ",
"         .$@O+++++.XXooooooo.+++$@@@@@.         ",
"         .$@O++++++.XXooooooo.++$@@@@@.         ",
"         .$@O+++++++.XXooooooo.+$@@@@@.         ",
"         .$@O++++++++.XXooooooo.$@@@@@.         ",
"        ..$#$$$$$$$$$$.XXooooooo.@@@@@.....     ",
"       .#.$############.XXooooooo.@@@.##$$@.    ",
"      .##.$#############.XXooooooo.@.##$$@@.    ",
"     .###.#@@@@@@@@@@@@@@.XXooooooo.##$$@@@.    ",
"    .####..................XXooooooo.$$@@@@.    ",
"   .$$$$$$$$$$$$$$$$$$$$$$$.XXooooooo.#@@@@.    ",
"   .$$$$$$$$$$$$$$$$$$$$$$$$.XXooooooo.@@@@.    ",
"   .$$#######################.XXooooooo.@@@.    ",
"   .$$########################.XXooooooo.@@.    ",
"   .$$#########################.XXooooooo..     ",
"   .$$##################.........XXooooooo.     ",
"   .##@@@@@@@@@@@@@@@@@@@@@@@@@@@.XXooooooo.    ",
"   .##@@@@@@@@@@@@@@@@@@@@@@@@@@@@.XXooooooo.   ",
"    ................................XXooooo.    ",
"                                    .XXooo.     ",
"                                     .XXo.      ",
"                                      .X.       ",
"                                       .        ",
"                                                ",
"                                                ",
"                                                "
};

const char *const *const cfg_icon[] = {
    cfg_icon_0,
    cfg_icon_1,
    cfg_icon_2,
};
const int n_cfg_icon = 3;
