/* XPM */
static const char *const main_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 6 1 ",
"  c None",
". c black",
"X c blue",
"o c #808080",
"O c #C0C0C0",
"+ c white",
/* pixels */
"                ",
"   .........    ",
"  .+++++++Oo.   ",
"  .+XXXXXXOo.   ",
"  .+XXXXXXOo.   ",
"  .+XXXXXXOo.   ",
"  .+XXXXXXOo.   ",
"  .+XXXXXXOo.   ",
"  .OOOOOOOOo..  ",
" .oooooooooo+o. ",
".+++++++++++Oo. ",
".+OOOOOooooOoo. ",
".Oooooooooooo.  ",
" ............   ",
"                ",
"                "
};

/* XPM */
static const char *const main_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 7 1 ",
"  c None",
". c black",
"X c navy",
"o c blue",
"O c #808080",
"+ c #C0C0C0",
"@ c white",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"         .................      ",
"        .++++++++++++++++O.     ",
"       .++++++++++++++++OO.     ",
"      .@@@@@@@@@@@@@@@+OOO.     ",
"      .@XXXXXXXXXXXXXX+OOO.     ",
"      .@Xooooooooooooo+OOO.     ",
"      .@Xooooooooooooo+OOO.     ",
"      .@Xooooooooooooo+OOO.     ",
"      .@Xooooooooooooo+OOO.     ",
"      .@Xooooooooooooo+OOO.     ",
"      .@Xooooooooooooo+OOO.     ",
"      .@Xooooooooooooo+OOO.     ",
"      .@Xooooooooooooo+OOO.     ",
"      .@@@@@@@@@@@@@@@+OOO...   ",
"     ..@++++++++++++++OOO.+@O.  ",
"    .+.+OOOOOOOOOOOOOOOO.+@OO.  ",
"   .++..................+@OOO.  ",
"  .@@@@@@@@@@@@@@@@@@@@@@+OOO.  ",
"  .@+++++++++++++++++++++OOOO.  ",
"  .@+++++++++++++++++++++OOO.   ",
"  .@++++++++++++O......O+OO.    ",
"  .+OOOOOOOOOOOOOOOOOOOOOO.     ",
"   .......................      ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "
};

/* XPM */
static const char *const main_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 7 1 ",
"  c None",
". c black",
"X c navy",
"o c blue",
"O c #808080",
"+ c #C0C0C0",
"@ c white",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"             .........................          ",
"            .++++++++++++++++++++++++O.         ",
"           .++++++++++++++++++++++++OO.         ",
"          .++++++++++++++++++++++++OOO.         ",
"         .@@@@@@@@@@@@@@@@@@@@@@@+OOOO.         ",
"         .@OOOOOOOOOOOOOOOOOOOOO+OOOOO.         ",
"         .@OXXXXXXXXXXXXXXXXXXXX@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"         .@OXooooooooooooooooooo@OOOOO.         ",
"        ..@+@@@@@@@@@@@@@@@@@@@@@OOOOO.....     ",
"       .+.@++++++++++++++++++++++OOOO.++@@O.    ",
"      .++.@++++++++++++++++++++++OOO.++@@OO.    ",
"     .+++.+OOOOOOOOOOOOOOOOOOOOOOOO.++@@OOO.    ",
"    .++++..........................++@@OOOO.    ",
"   .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+OOOO.    ",
"   .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+OOOOO.    ",
"   .@@+++++++++++++++++++++++++++++++OOOOOO.    ",
"   .@@+++++++++++++++++++++++++++++++OOOOOO.    ",
"   .@@+++++++++++++++++++++++++++++++OOOOO.     ",
"   .@@++++++++++++++++++..........O++OOOO.      ",
"   .++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.       ",
"   .++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.        ",
"    ...................................         ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "
};

const char *const *const main_icon[] = {
    main_icon_0,
    main_icon_1,
    main_icon_2,
};
const int n_main_icon = 3;
